[phases.setup]
nixPkgs = ["nss", "nspr", "atk", "cups", "libdrm", "gtk3", "pango", "cairo", "glib", "dbus", "alsa-lib", "at-spi2-atk", "xorg.libX11", "xorg.libXcomposite", "xorg.libXdamage", "xorg.libXext", "xorg.libXfixes", "xorg.libXrandr", "xorg.libxcb", "mesa", "expat", "xorg.libxshmfence", "gdk-pixbuf"]
