CREATE TABLE `agent_checklist_templates` (
  `id` int NOT NULL AUTO_INCREMENT,
  `ownerUserId` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` text NULL,
  `targetType` enum('transaction','listing') NOT NULL,
  `transactionTypeFilter` enum('buyer','seller','dual','any') NOT NULL DEFAULT 'any',
  `automaticDefaultEvent` enum('none','on_create','on_under_contract') NOT NULL DEFAULT 'none',
  `archivedAt` timestamp NULL,
  `archivedByUserId` int NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `agent_checklist_templates_owner_archived_idx` (`ownerUserId`,`archivedAt`),
  KEY `agent_checklist_templates_auto_match_idx` (`ownerUserId`,`targetType`,`automaticDefaultEvent`,`archivedAt`),
  CONSTRAINT `agent_checklist_templates_owner_fk` FOREIGN KEY (`ownerUserId`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `agent_checklist_templates_archived_by_fk` FOREIGN KEY (`archivedByUserId`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `agent_checklist_template_items` (
  `id` int NOT NULL AUTO_INCREMENT,
  `templateId` int NOT NULL,
  `title` varchar(500) NOT NULL,
  `notes` text NULL,
  `sectionName` varchar(255) NOT NULL DEFAULT 'General',
  `sortOrder` int NOT NULL DEFAULT 0,
  `dueAnchor` enum('target_created','under_contract','closing','listing_live') NULL,
  `dueOffsetDays` int NOT NULL DEFAULT 0,
  `assignmentType` enum('none','owner','specific') NOT NULL DEFAULT 'none',
  `assignedUserId` int NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `agent_checklist_template_items_order_idx` (`templateId`,`sortOrder`,`id`),
  KEY `agent_checklist_template_items_assignee_idx` (`assignedUserId`),
  CONSTRAINT `agent_checklist_template_items_template_fk` FOREIGN KEY (`templateId`) REFERENCES `agent_checklist_templates` (`id`) ON DELETE CASCADE,
  CONSTRAINT `agent_checklist_template_items_assignee_fk` FOREIGN KEY (`assignedUserId`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `agent_checklist_template_shares` (
  `id` int NOT NULL AUTO_INCREMENT,
  `templateId` int NOT NULL,
  `sharedWithUserId` int NOT NULL,
  `sharedByUserId` int NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `agent_checklist_template_shares_unique` (`templateId`,`sharedWithUserId`),
  KEY `agent_checklist_template_shares_user_idx` (`sharedWithUserId`,`templateId`),
  CONSTRAINT `agent_checklist_template_shares_template_fk` FOREIGN KEY (`templateId`) REFERENCES `agent_checklist_templates` (`id`) ON DELETE CASCADE,
  CONSTRAINT `agent_checklist_template_shares_recipient_fk` FOREIGN KEY (`sharedWithUserId`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `agent_checklist_template_shares_actor_fk` FOREIGN KEY (`sharedByUserId`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `agent_checklist_applications` (
  `id` int NOT NULL AUTO_INCREMENT,
  `templateId` int NULL,
  `transactionId` int NULL,
  `listingId` int NULL,
  `targetType` enum('transaction','listing') NOT NULL,
  `source` enum('auto','manual') NOT NULL,
  `autoKey` varchar(255) NULL,
  `templateNameSnapshot` varchar(255) NOT NULL,
  `templateDescriptionSnapshot` text NULL,
  `templateOwnerUserIdSnapshot` int NOT NULL,
  `templateTargetTypeSnapshot` enum('transaction','listing') NOT NULL,
  `templateTransactionTypeFilterSnapshot` enum('buyer','seller','dual','any') NOT NULL,
  `templateAutomaticDefaultEventSnapshot` enum('none','on_create','on_under_contract') NOT NULL,
  `targetAgentUserIdSnapshot` int NULL,
  `appliedByUserId` int NULL,
  `removedAt` timestamp NULL,
  `removedByUserId` int NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `agent_checklist_applications_autoKey_unique` (`autoKey`),
  KEY `agent_checklist_applications_transaction_idx` (`transactionId`,`removedAt`,`createdAt`),
  KEY `agent_checklist_applications_listing_idx` (`listingId`,`removedAt`,`createdAt`),
  KEY `agent_checklist_applications_template_idx` (`templateId`),
  CONSTRAINT `agent_checklist_applications_exact_target_chk` CHECK (((`transactionId` IS NOT NULL AND `listingId` IS NULL AND `targetType` = 'transaction') OR (`transactionId` IS NULL AND `listingId` IS NOT NULL AND `targetType` = 'listing'))),
  CONSTRAINT `agent_checklist_applications_template_fk` FOREIGN KEY (`templateId`) REFERENCES `agent_checklist_templates` (`id`) ON DELETE SET NULL,
  CONSTRAINT `agent_checklist_applications_transaction_fk` FOREIGN KEY (`transactionId`) REFERENCES `transactions` (`id`) ON DELETE CASCADE,
  CONSTRAINT `agent_checklist_applications_listing_fk` FOREIGN KEY (`listingId`) REFERENCES `listings` (`id`) ON DELETE CASCADE,
  CONSTRAINT `agent_checklist_applications_applied_by_fk` FOREIGN KEY (`appliedByUserId`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `agent_checklist_applications_removed_by_fk` FOREIGN KEY (`removedByUserId`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `agent_checklist_application_items` (
  `id` int NOT NULL AUTO_INCREMENT,
  `applicationId` int NOT NULL,
  `templateItemId` int NULL,
  `title` varchar(500) NOT NULL,
  `notes` text NULL,
  `sectionName` varchar(255) NOT NULL DEFAULT 'General',
  `sortOrder` int NOT NULL DEFAULT 0,
  `dueAnchorSnapshot` enum('target_created','under_contract','closing','listing_live') NULL,
  `dueOffsetDaysSnapshot` int NOT NULL DEFAULT 0,
  `assignmentTypeSnapshot` enum('none','owner','specific') NOT NULL DEFAULT 'none',
  `configuredAssignedUserIdSnapshot` int NULL,
  `dueDate` timestamp NULL,
  `dueDateManuallyOverridden` boolean NOT NULL DEFAULT false,
  `assignedUserId` int NULL,
  `completed` boolean NOT NULL DEFAULT false,
  `completedAt` timestamp NULL,
  `completedByUserId` int NULL,
  `removedAt` timestamp NULL,
  `removedByUserId` int NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `agent_checklist_application_items_order_idx` (`applicationId`,`removedAt`,`sortOrder`,`id`),
  KEY `agent_checklist_application_items_assignee_due_idx` (`assignedUserId`,`completed`,`dueDate`),
  KEY `agent_checklist_application_items_template_item_idx` (`templateItemId`),
  CONSTRAINT `agent_checklist_application_items_application_fk` FOREIGN KEY (`applicationId`) REFERENCES `agent_checklist_applications` (`id`) ON DELETE CASCADE,
  CONSTRAINT `agent_checklist_application_items_template_item_fk` FOREIGN KEY (`templateItemId`) REFERENCES `agent_checklist_template_items` (`id`) ON DELETE SET NULL,
  CONSTRAINT `agent_checklist_application_items_assignee_fk` FOREIGN KEY (`assignedUserId`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `agent_checklist_application_items_completed_by_fk` FOREIGN KEY (`completedByUserId`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `agent_checklist_application_items_removed_by_fk` FOREIGN KEY (`removedByUserId`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
