CREATE TABLE IF NOT EXISTS `resend_webhook_events` (
  `id` int NOT NULL AUTO_INCREMENT,
  `svixId` varchar(255) NOT NULL,
  `eventType` varchar(64) NOT NULL,
  `providerMessageId` varchar(255) NULL,
  `broadcastId` varchar(255) NULL,
  `payload` json NOT NULL,
  `status` enum('pending','processing','processed') NOT NULL DEFAULT 'pending',
  `attemptCount` int NOT NULL DEFAULT 0,
  `availableAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `leaseToken` varchar(128) NULL,
  `leaseExpiresAt` timestamp NULL,
  `processedAt` timestamp NULL,
  `errorMessage` text NULL,
  `receivedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `resend_webhook_events_svix_id_unique` (`svixId`),
  KEY `resend_webhook_events_status_available_idx` (`status`,`availableAt`,`id`),
  KEY `resend_webhook_events_message_idx` (`providerMessageId`),
  KEY `resend_webhook_events_broadcast_idx` (`broadcastId`),
  KEY `resend_webhook_events_lease_idx` (`leaseExpiresAt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
