import { Link } from "wouter";
import { ChevronRight, KeyRound, Plus, Settings2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";

export default function PulseSettingsHubPage() {
  const shell = trpc.pulse.shell.useQuery();
  const meetings = trpc.pulse.list.useQuery(undefined, { enabled: Boolean(shell.data?.canManageL10s) });
  if (shell.isLoading) return <main className="mx-auto max-w-4xl space-y-4"><Skeleton className="h-24 w-full"/><Skeleton className="h-48 w-full"/></main>;
  if (!shell.data?.canSeeSettings) return <main className="mx-auto max-w-3xl"><Card><CardContent className="p-6"><p className="font-medium">Pulse settings are not available.</p><p className="mt-2 text-sm text-muted-foreground">Ask a Pulse permission-matrix administrator to grant the capability you need.</p><Button asChild className="mt-4"><Link href="/pulse">Return to Pulse</Link></Button></CardContent></Card></main>;
  const l10s = (meetings.data ?? []).filter((meeting: any) => meeting.label === "level_10");
  return <main className="mx-auto max-w-4xl space-y-6 pb-10"><header className="border-b border-border pb-5"><p className="text-sm font-medium text-primary">Pulse</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">L10 settings</h1><p className="mt-2 max-w-3xl text-base text-muted-foreground">Pulse permissions control what you can manage. Active membership controls which L10 workspace and history you can see.</p></header>{shell.data.canManagePermissionMatrix ? <Card className="border-primary/20 bg-primary/[0.03]"><CardHeader><CardTitle className="flex items-center gap-2"><KeyRound className="h-5 w-5 text-primary"/>Pulse permission matrix</CardTitle><CardDescription>Grant or revoke every Pulse capability. This matrix is self-governing and independent from SavvyOS roles.</CardDescription></CardHeader><CardContent><Button asChild variant="outline"><Link href="/pulse/settings/permissioning">Open permission matrix</Link></Button></CardContent></Card> : null}{shell.data.canManageL10s ? <Card><CardHeader><CardTitle className="flex items-center gap-2"><Settings2 className="h-5 w-5 text-primary"/>Recurring L10 workspaces</CardTitle><CardDescription>Configure the L10s that you are a participant in. Archiving preserves all sessions, reports, items, and audit history.</CardDescription></CardHeader><CardContent className="space-y-3"><Button asChild><Link href="/pulse/settings/create"><Plus className="mr-2 h-4 w-4"/>Create L10</Link></Button><div className="divide-y rounded-xl border">{meetings.isLoading ? <Skeleton className="m-3 h-14"/> : l10s.length ? l10s.map((meeting: any) => <Link key={meeting.id} href={`/pulse/settings/meetings/${meeting.id}`} className="flex min-h-14 items-center gap-3 p-4 transition-colors hover:bg-muted/60"><div className="min-w-0 flex-1"><p className="truncate font-medium">{meeting.name}</p><p className="mt-1 text-sm text-muted-foreground">{meeting.dayOfWeek ? `${meeting.dayOfWeek.slice(0, 1).toUpperCase()}${meeting.dayOfWeek.slice(1)}s` : meeting.cadence} · {meeting.durationMinutes} minutes</p></div><ChevronRight className="h-5 w-5 text-muted-foreground"/></Link>) : <p className="p-5 text-sm text-muted-foreground">You are not a participant in an active L10 yet. Create one or ask its manager to add you.</p>}</div></CardContent></Card> : null}{!shell.data.canManageL10s && !shell.data.canManagePermissionMatrix ? <Card><CardContent className="p-6 text-sm text-muted-foreground">Your Pulse access currently permits participation only. You can work in the L10s you belong to, but a matrix administrator must grant management or matrix capability for settings.</CardContent></Card> : null}</main>;
}
