import { Link } from "wouter";
import { ArrowLeft, KeyRound, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { Switch } from "@/components/ui/switch";
import { trpc } from "@/lib/trpc";

const capabilities: Record<string, { label: string; description: string }> = {
  manage_permission_matrix: { label: "Manage permission matrix", description: "View this matrix and grant or revoke every other Pulse permission." },
  manage_l10s: { label: "Manage L10s", description: "Create, configure, archive, reactivate, manage participants, and map Scorecard Metrics and Rock visibility for member L10s." },
  run_l10s: { label: "Run L10s", description: "Start, pause, advance, and close member L10 sessions, including publishing their prepared cascades." },
  view_all_l10_health: { label: "View all L10 health", description: "Review aggregate cadence and outcome health without bypassing membership for work-item data." },
};

export default function PulsePermissioningPage() {
  const matrix = trpc.pulse.l10.permissionMatrix.useQuery();
  const update = trpc.pulse.l10.setPermission.useMutation({ onSuccess: () => void matrix.refetch(), onError: (error) => toast.error(error.message) });
  if (matrix.isLoading) return <main className="mx-auto max-w-6xl space-y-4"><Skeleton className="h-24 w-full"/><Skeleton className="h-96 w-full"/></main>;
  if (matrix.error || !matrix.data) return <main className="mx-auto max-w-3xl"><Card><CardContent className="p-6">The Pulse permission matrix is not available.</CardContent></Card></main>;
  const grantFor = (personId: number, capability: string) => matrix.data.grants.find((grant: any) => grant.personId === personId && grant.capability === capability)?.allowed === true;
  return <main className="mx-auto max-w-6xl space-y-6 pb-10"><header className="border-b border-border pb-5"><Button asChild variant="ghost" className="-ml-3 min-h-11"><Link href="/pulse/settings"><ArrowLeft className="mr-2 h-4 w-4"/>Pulse settings</Link></Button><p className="mt-3 text-sm font-medium text-primary">Pulse governance</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Permission matrix</h1><p className="mt-2 max-w-4xl text-base text-muted-foreground">Pulse authority comes from this matrix and active L10 membership. For SavvyOS administrators, the Pulse Settings Super Permission grants matrix-administrator access; the matrix controls the remaining Pulse capabilities. A person with the first permission can administer this matrix.</p></header><Card className="border-primary/20 bg-primary/[0.03]"><CardContent className="flex gap-3 p-5"><ShieldCheck className="h-6 w-6 shrink-0 text-primary"/><p className="text-sm leading-6">Keep at least one <strong>Manage permission matrix</strong> holder. Pulse prevents the last matrix administrator from removing their own access so the module cannot be locked permanently.</p></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><KeyRound className="h-5 w-5 text-primary"/>Pulse capabilities</CardTitle><CardDescription>Toggle a permission to grant or revoke it immediately. Meeting visibility remains independently governed by each L10’s participant list.</CardDescription></CardHeader><CardContent className="overflow-x-auto"><table className="min-w-[900px] w-full text-sm"><thead className="border-b text-left"><tr><th className="pb-3 pr-4 font-medium">Person</th>{matrix.data.capabilityKeys.map((capability) => <th className="min-w-48 pb-3 pr-4 align-bottom font-medium" key={capability}><span className="block">{capabilities[capability]?.label ?? capability}</span><span className="mt-1 block text-xs font-normal leading-4 text-muted-foreground">{capabilities[capability]?.description}</span></th>)}</tr></thead><tbody>{matrix.data.people.map((person: any) => <tr key={person.id} className="border-b last:border-0"><td className="py-4 pr-4 align-top"><p className="font-medium">{person.name ?? person.email}</p><p className="mt-1 text-xs text-muted-foreground">{person.email}</p></td>{matrix.data.capabilityKeys.map((capability) => { const allowed = grantFor(person.id, capability); return <td className="py-4 pr-4 align-top" key={capability}><label className="flex items-center gap-2"><Switch aria-label={`${allowed ? "Revoke" : "Grant"} ${capabilities[capability]?.label ?? capability} for ${person.name ?? person.email}`} checked={allowed} disabled={update.isPending} onCheckedChange={(next) => update.mutate({ personId: person.id, capability, allowed: next })}/><span className="text-xs text-muted-foreground">{allowed ? "Granted" : "Not granted"}</span></label></td>; })}</tr>)}</tbody></table></CardContent></Card></main>;
}
