import { useMemo, useState } from "react";
import { Link } from "wouter";
import { Check, ChevronDown, Send } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";

const weekLabel = (value: any) => new Date(value).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" });

function Field({ field, onSaved }: { field: any; onSaved: () => void }) {
  const [value, setValue] = useState(field.value ?? "");
  const [tone, setTone] = useState(field.tone ?? "green");
  const [saved, setSaved] = useState(false);
  const save = trpc.pulse.personal.saveInput.useMutation({ onSuccess: () => { setSaved(true); onSaved(); window.setTimeout(() => setSaved(false), 1600); }, onError: (error) => toast.error(error.message) });
  const submit = () => { if (field.kind === "number" && value === "") return; if (field.kind === "text" && field.required && !String(value).trim()) return; if (value !== field.value || (field.updateType === "headline" && tone !== field.tone)) save.mutate({ key: field.key, value: field.kind === "number" ? Number(value) : String(value), meetingId: field.meetingId, tone }); };
  const title = <span className="flex items-start justify-between gap-3"><span><span className="block text-base font-medium">{field.label}{field.required ? <span className="ml-1 text-destructive">*</span> : null}</span><span className="mt-0.5 block text-sm text-muted-foreground">{field.kind === "number" ? `${field.source === "automatic" ? "Review source metric" : "Enter this week’s value"}` : field.updateType === "segue" ? "Share a win, a personal note, or a quick check-in." : "Optional news that matters to this L10."}</span></span>{field.target !== undefined ? <span className="shrink-0 text-sm text-muted-foreground">Target {field.target ?? "—"}</span> : null}</span>;
  return <div className="border-t border-border py-4 first:border-t-0">{title}{field.kind === "number" ? <Input aria-label={field.label} className="mt-3 min-h-11 text-base" inputMode="decimal" type="number" value={value} onChange={(event) => setValue(event.target.value)} onBlur={submit} onKeyDown={(event) => { if (event.key === "Enter") (event.currentTarget as HTMLInputElement).blur(); }} /> : <><Textarea aria-label={field.label} className="mt-3 min-h-24 text-base" value={value} onChange={(event) => setValue(event.target.value)} onBlur={submit} placeholder={field.updateType === "segue" ? "Share your Segue…" : "Share a Headline…"} />{field.updateType === "headline" ? <div className="mt-2 flex flex-wrap gap-2"><Label className="pt-2 text-sm text-muted-foreground">Status</Label>{[["green", "On track"], ["amber", "Watch"], ["red", "Needs attention"]].map(([id, label]) => <button key={id} type="button" onClick={() => { setTone(id); window.setTimeout(submit, 0); }} className={`min-h-9 rounded-full border px-3 text-sm ${tone === id ? id === "green" ? "border-emerald-600 bg-emerald-50 text-emerald-800" : id === "amber" ? "border-amber-600 bg-amber-50 text-amber-800" : "border-rose-600 bg-rose-50 text-rose-800" : "border-border"}`}>{label}</button>)}</div> : null}</>}<span aria-live="polite" className="mt-2 flex h-4 items-center text-xs text-emerald-700">{saved ? <><Check className="mr-1 h-3 w-3" />Saved</> : null}</span></div>;
}

export default function PulseMyInputsPage() {
  const utils = trpc.useUtils();
  const { data, isLoading, error } = trpc.pulse.personal.inputs.useQuery();
  const [selectedId, setSelectedId] = useState<string>("");
  const submit = trpc.pulse.personal.submitWeeklyPrep.useMutation({ onSuccess: () => { toast.success("Weekly Prep confirmed. A confirmation email is on its way."); void utils.pulse.personal.inputs.invalidate(); }, onError: (error) => toast.error(error.message) });
  const withdraw = trpc.pulse.personal.withdrawWeeklyPrep.useMutation({ onSuccess: () => { toast("Weekly Prep reopened for edits."); void utils.pulse.personal.inputs.invalidate(); }, onError: (error) => toast.error(error.message) });
  const selectedMeeting = useMemo(() => { const meetings = data?.meetings ?? []; return meetings.find((meeting: any) => meeting.id === selectedId) ?? meetings[0]; }, [data?.meetings, selectedId]);
  if (isLoading) return <main className="mx-auto max-w-3xl space-y-4"><Skeleton className="h-24 w-full" /><Skeleton className="h-96 w-full" /></main>;
  if (error || !data) return <main className="mx-auto max-w-3xl"><Card><CardContent className="p-6">Weekly Prep is not available right now.</CardContent></Card></main>;
  if (!selectedMeeting) return <main className="mx-auto max-w-3xl"><Card><CardContent className="p-6"><p className="font-medium">You are not assigned to an L10 yet.</p><p className="mt-2 text-muted-foreground">When you are added to a Pulse L10, your weekly preparation will appear here.</p></CardContent></Card></main>;
  const fields = data.fields.filter((field: any) => field.meetingId === selectedMeeting.id);
  const required = fields.filter((field: any) => field.required);
  const complete = required.every((field: any) => field.value !== null && String(field.value).trim() !== "");
  return <main className="mx-auto max-w-3xl space-y-5 pb-10"><header className="border-b border-border pb-5"><p className="text-sm font-medium text-primary">Pulse · Week of {weekLabel(data.weekOf)}</p><h1 className="mt-1 text-2xl font-semibold tracking-tight sm:text-3xl">Weekly Prep</h1><p className="mt-2 max-w-2xl text-base leading-6 text-muted-foreground">Prepare each L10 before it starts. Your current values and notes stay editable until you confirm them for that meeting.</p></header><div className="flex flex-wrap gap-2 border-b border-border pb-3">{data.meetings.slice(0, 4).map((meeting: any) => <Button key={meeting.id} type="button" variant={meeting.id === selectedMeeting.id ? "default" : "outline"} className="min-h-11" onClick={() => setSelectedId(meeting.id)}>{meeting.name}{meeting.submitted ? <Check className="ml-2 h-4 w-4" /> : null}</Button>)}{data.meetings.length > 4 ? <Select value={selectedMeeting.id} onValueChange={setSelectedId}><SelectTrigger className="min-h-11 w-48"><ChevronDown className="mr-2 h-4 w-4" /><SelectValue placeholder="More meetings" /></SelectTrigger><SelectContent>{data.meetings.slice(4).map((meeting: any) => <SelectItem key={meeting.id} value={meeting.id}>{meeting.name}</SelectItem>)}</SelectContent></Select> : null}</div><Card><CardHeader><CardTitle>{selectedMeeting.name}</CardTitle><CardDescription>{selectedMeeting.submitted ? "Confirmed for this week. You can withdraw it to make edits." : complete ? "Required items are ready to confirm." : `${required.filter((field: any) => field.value === null || String(field.value).trim() === "").length} required item${required.length === 1 ? "" : "s"} still needs attention.`}</CardDescription></CardHeader><CardContent className="space-y-1">{fields.map((field: any) => <Field key={field.key} field={field} onSaved={() => void utils.pulse.personal.inputs.invalidate()} />)}<div className="mt-3 flex flex-col-reverse gap-3 border-t border-border pt-4 sm:flex-row sm:justify-between"><Button asChild variant="outline" className="min-h-11"><Link href="/pulse/dashboard">My EOS Dashboard</Link></Button>{selectedMeeting.submitted ? <Button variant="outline" className="min-h-11" disabled={withdraw.isPending} onClick={() => withdraw.mutate({ meetingId: selectedMeeting.id })}>Withdraw confirmation</Button> : <Button className="min-h-11" disabled={!complete || submit.isPending} onClick={() => submit.mutate({ meetingId: selectedMeeting.id })}>{submit.isPending ? "Confirming…" : <><Send className="mr-2 h-4 w-4" />Confirm Weekly Prep</>}</Button>}</div></CardContent></Card></main>;
}
