import { useState } from "react";
import { Link } from "wouter";
import { Check, ChevronDown, Circle, Clock3, Plus, Target } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";
import { PulseCascadeCard } from "@/components/pulse/PulseCascadeCard";
import { PulseScorecard } from "@/components/pulse/PulseScorecard";
import { PulseGoals } from "@/components/pulse/PulseGoals";
import { PulseNeedsAttention } from "@/components/pulse/PulseNeedsAttention";
import { PulseProposedIssues } from "@/components/pulse/PulseProposedIssues";

const title: Record<string, string> = { segue: "This week's shares", headlines: "Headlines", scorecard: "My numbers this week", goals: "Goals", rocks: "Rocks", todos: "To-dos", issues: "Issues", cascading: "Messages for this meeting", conclude: "Last meeting" };
function nextMeeting(day?: string | null) { if (!day) return "Schedule not set"; const days = ["sunday","monday","tuesday","wednesday","thursday","friday","saturday"]; const target = days.indexOf(day); const delta = (target - new Date().getDay() + 7) % 7 || 7; return `Next meeting in ${delta === 1 ? "1 day" : `${delta} days`}`; }
function emptyCopy(section: string) { return { segue: "No shares yet. Add the useful thing your teammates need to hear.", headlines: "No headlines yet. Add what changes the conversation.", scorecard: "No numbers are set up yet.", goals: "No goals are assigned to this meeting yet.", rocks: "No rocks are set yet. Add the goal that matters this quarter.", todos: "No to-dos are open. Add the next clear step when one appears.", issues: "No issues are open. Add the decision this meeting needs to make.", cascading: "No messages are waiting for this meeting.", conclude: "No prior meeting summary is available yet." }[section] ?? "Nothing is here yet."; }

function Todo({ item, invalidate }: { item: any; invalidate: () => void }) {
  const mutation = trpc.pulse.workItems.setTodoStatus.useMutation({ onSuccess: invalidate });
  return <div className="flex min-h-11 items-center gap-3 py-2"><button type="button" aria-label={`Mark ${item.title} ${item.status === "done" ? "open" : "done"}`} aria-pressed={item.status === "done"} onClick={() => mutation.mutate({ workItemId: item.id, status: item.status === "done" ? "open" : "done" })} className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full border border-border focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring">{item.status === "done" ? <Check className="h-5 w-5 text-emerald-600" /> : <Circle className="h-5 w-5 text-muted-foreground" />}</button><div className="min-w-0 flex-1"><p className={`text-base font-medium ${item.status === "done" ? "text-muted-foreground line-through" : "text-foreground"}`}>{item.title}</p><p className="text-sm text-muted-foreground">{item.assigneeName ?? "Meeting member"}{item.dueDate ? ` · due ${new Date(item.dueDate).toLocaleDateString(undefined,{month:"short",day:"numeric"})}` : ""}</p></div></div>;
}
function Rock({ item, invalidate, mine }: { item: any; invalidate: () => void; mine: boolean }) {
  const mutation = trpc.pulse.workItems.setManualRockPercent.useMutation({ onSuccess: invalidate });
  const [value, setValue] = useState(String(item.percentComplete ?? 0));
  return <div className="py-3"><div className="flex items-start justify-between gap-3"><div><p className="text-base font-medium">{item.title}</p><p className="text-sm text-muted-foreground">{item.assigneeName ?? "Meeting member"} · {item.status.replaceAll("_", " ")}</p>{item.readOnly && <p className="mt-1 text-xs text-muted-foreground">Read-only · owned in {item.homeMeetingName}</p>}</div><span className="text-sm font-semibold">{item.percentComplete}%</span></div><Progress className="mt-2 h-2" value={item.percentComplete} />{mine && item.percentSource === "manual" && <label className="mt-3 flex items-center gap-2 text-sm">Update progress <Input aria-label={`Update ${item.title} progress`} className="min-h-11 w-20" type="number" min="0" max="100" value={value} onChange={(e) => setValue(e.target.value)} onBlur={() => mutation.mutate({ workItemId: item.id, percentComplete: Math.max(0, Math.min(100, Number(value) || 0)) })} /></label>}</div>;
}
function DashboardSection({ section, meetingId, viewerId, canSendCascades, visibleMeetings, invalidate }: { section: any; meetingId: string; viewerId: number; canSendCascades: boolean; visibleMeetings: Array<{ id: string; name: string }>; invalidate: () => void }) {
  const [text, setText] = useState(""); const [issue, setIssue] = useState(""); const [cascadeBody, setCascadeBody] = useState(""); const [cascadeTargets, setCascadeTargets] = useState<string[]>([]); const utils = trpc.useUtils();
  const addUpdate = trpc.pulse.meetingViews.addUpdate.useMutation({ onSuccess: invalidate });
  const addIssue = trpc.pulse.workItems.create.useMutation({ onSuccess: () => { invalidate(); utils.pulse.workItems.list.invalidate(); } });
  const acknowledge = trpc.pulse.cascades.acknowledge.useMutation({ onSuccess: invalidate });
  const sendCascade = trpc.pulse.cascades.send.useMutation({ onSuccess: () => { setCascadeBody(""); setCascadeTargets([]); invalidate(); } });
  const items = section.items ?? [];
  return <section className="border-t border-border pt-5 first:border-t-0 first:pt-0" aria-labelledby={`section-${section.section}`}><div className="mb-3 flex items-center justify-between gap-3"><h2 id={`section-${section.section}`} className="text-base font-semibold">{title[section.section]}</h2><span className="text-sm text-muted-foreground">{items.length ? `${items.length} ${items.length === 1 ? "item" : "items"}` : ""}</span></div>
    {!items.length && <p className="rounded-lg bg-muted/60 p-3 text-sm leading-5 text-muted-foreground">{emptyCopy(section.section)}</p>}
    {section.section === "todos" && <div>{items.sort((a:any,b:any)=>Number(b.assigneeId===viewerId)-Number(a.assigneeId===viewerId)).map((item:any)=><Todo key={item.id} item={item} invalidate={invalidate} />)}</div>}
    {section.section === "rocks" && <div className="divide-y divide-border">{items.map((item:any)=><Rock key={item.id} item={item} mine={item.assigneeId===viewerId && !item.readOnly} invalidate={invalidate} />)}</div>}
    {section.section === "issues" && <div className="space-y-2">{items.map((item:any)=><div key={item.id} className="rounded-lg bg-muted/50 p-3"><p className="font-medium">{item.title}</p><p className="text-sm text-muted-foreground">{item.assigneeName ?? "Meeting member"} · {item.status}</p></div>)}<PulseProposedIssues proposals={section.meta?.proposals ?? []} onChanged={invalidate} /><form className="mt-3 flex gap-2" onSubmit={(e)=>{e.preventDefault();if(issue.trim()) {addIssue.mutate({type:"issue",title:issue.trim(),meetingId,ownerPersonId:null});setIssue("");}}}><Input aria-label="Add an issue" className="min-h-11" value={issue} onChange={(e)=>setIssue(e.target.value)} placeholder="What needs a decision?"/><Button type="submit" className="min-h-11 shrink-0"><Plus className="mr-1 h-4 w-4"/>Add issue</Button></form></div>}
    {section.section === "scorecard" && <PulseScorecard section={section} meetingId={meetingId} canConfigure={canSendCascades} onChanged={invalidate} />}
    {section.section === "goals" && <PulseGoals section={section} meetingId={meetingId} canConfigure={canSendCascades} onChanged={invalidate} />}
    {(section.section === "segue" || section.section === "headlines") && <div className="space-y-2">{items.map((item:any)=><p key={item.id} className="rounded-lg bg-muted/50 p-3 text-sm"><span className="font-medium">{item.authorName ?? "A teammate"}: </span>{item.body}</p>)}<form className="mt-3 flex gap-2" onSubmit={(e)=>{e.preventDefault();if(text.trim()){addUpdate.mutate({meetingId,updateType:section.section,body:text.trim()});setText("")}}}><Input aria-label={`Add ${section.section === "segue" ? "a share" : "a headline"}`} className="min-h-11" value={text} onChange={(e)=>setText(e.target.value)} placeholder={section.meta.prompt}/><Button type="submit" variant="outline" className="min-h-11">Add</Button></form></div>}
    {section.section === "cascading" && <div className="space-y-3">{items.map((item:any)=><PulseCascadeCard key={item.id} message={item} isAcknowledging={acknowledge.isPending} onAcknowledge={(messageId) => acknowledge.mutate({ messageId, from: "meeting_dashboard" })} />)}{canSendCascades && <form className="rounded-lg border border-dashed border-border p-3" onSubmit={(event) => { event.preventDefault(); if (cascadeBody.trim() && cascadeTargets.length) sendCascade.mutate({ fromMeetingId: meetingId, toMeetingIds: cascadeTargets, body: cascadeBody.trim() }); }}><p className="font-medium">Send to another meeting</p><p className="mt-1 text-sm text-muted-foreground">Recipients must already be able to see this source meeting.</p><div className="mt-3 flex flex-wrap gap-2">{visibleMeetings.filter((meeting) => meeting.id !== meetingId).map((meeting) => { const selected = cascadeTargets.includes(meeting.id); return <Button key={meeting.id} type="button" size="sm" variant={selected ? "default" : "outline"} className="min-h-11" aria-pressed={selected} onClick={() => setCascadeTargets((targets) => selected ? targets.filter((target) => target !== meeting.id) : [...targets, meeting.id])}>{meeting.name}</Button>; })}</div><Input aria-label="Message for receiving meetings" className="mt-3 min-h-11" value={cascadeBody} onChange={(event) => setCascadeBody(event.target.value)} placeholder="What does the receiving meeting need to carry forward?"/><Button type="submit" className="mt-3 min-h-11" disabled={sendCascade.isPending || !cascadeTargets.length || !cascadeBody.trim()}>{sendCascade.isPending ? "Sending…" : "Send message"}</Button></form>}</div>}
    {!["todos","rocks","issues","scorecard","segue","headlines","cascading"].includes(section.section) && items.length > 0 && <div>{items.map((item:any)=><p key={item.id}>{item.title ?? item.body}</p>)}</div>}
  </section>;
}

export default function PulseMeetingDashboardPage({ meetingId }: { meetingId: string }) {
  const utils = trpc.useUtils(); const { data, isLoading, error } = trpc.pulse.meetingViews.dashboard.useQuery({ meetingId }); const { data: visibleMeetings = [] } = trpc.pulse.list.useQuery();
  const [showMore, setShowMore] = useState(false); const invalidate = () => utils.pulse.meetingViews.dashboard.invalidate({ meetingId });
  const sections = data?.sections ?? []; const visible = showMore ? sections : sections.slice(0,4);
  const viewerId = data?.viewerId ?? 0;
  const facilitator = data?.members?.find((member: any) => member.id === data.meeting.facilitatorId);
  const administrator = data?.members?.find((member: any) => member.id === data.meeting.administratorId);
  if (isLoading) return <div className="space-y-4"><Skeleton className="h-20 w-full"/><Skeleton className="h-72 w-full"/></div>;
  if (error || !data) return <Card><CardContent className="p-6">This meeting no longer exists. <Link className="underline" href="/pulse/meetings">Go to your meetings</Link>.</CardContent></Card>;
  return <main className="mx-auto max-w-3xl space-y-5"><Link href="/pulse/meetings" className="inline-flex min-h-11 items-center text-sm font-medium text-muted-foreground">Your meetings</Link><header className="border-b border-border pb-5"><div className="flex items-start justify-between gap-3"><div><h1 className="text-2xl font-semibold tracking-tight">{data.meeting.name}</h1><p className="mt-1 text-base text-muted-foreground">{data.meeting.dayOfWeek ? `${data.meeting.dayOfWeek}s ${data.meeting.startTime ?? ""}` : data.meeting.cadence} · {nextMeeting(data.meeting.dayOfWeek)}</p><div className="mt-3 grid gap-2 text-sm text-muted-foreground sm:grid-cols-2"><p><span className="font-medium text-foreground">Facilitator:</span> {facilitator?.name ?? "Not assigned"}</p><p><span className="font-medium text-foreground">Administrator:</span> {administrator?.name ?? "Not assigned"}</p><p className="sm:col-span-2"><span className="font-medium text-foreground">Attendees:</span> {data.members?.length ? data.members.map((member: any) => member.name).join(", ") : "No attendees added yet"}</p></div></div>{data.manager?.canRun && <Button asChild className="min-h-11"><Link href={`/pulse/meetings/${meetingId}/run`}><Clock3 className="mr-2 h-4 w-4"/>Run meeting</Link></Button>}</div></header><Card><CardContent className="space-y-5 p-4 sm:p-6">{visible.map((section:any)=><DashboardSection key={section.section} section={section} meetingId={meetingId} viewerId={viewerId} canSendCascades={Boolean(data.manager?.canRun)} visibleMeetings={visibleMeetings as Array<{ id: string; name: string }>} invalidate={invalidate}/>)}{sections.length>4 && <Button variant="ghost" type="button" className="min-h-11" onClick={()=>setShowMore(!showMore)}>{showMore ? "Show less" : `Show ${sections.length-4} more sections`}<ChevronDown className={`ml-2 h-4 w-4 ${showMore?"rotate-180":""}`}/></Button>}{data.manager?.canRun && <PulseNeedsAttention items={data.attention ?? []} />}</CardContent></Card></main>;
}
