import { useMemo, useState } from "react";
import { ArrowDown, ArrowRight, ArrowUp, ArrowLeft } from "lucide-react";
import { Link } from "wouter";
import { trpc } from "@/lib/trpc";
import { formatEasternDateTime } from "@/lib/format";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Skeleton } from "@/components/ui/skeleton";

function Trend({ value }: { value: "up" | "down" | "flat" }) {
  const Icon = value === "up" ? ArrowUp : value === "down" ? ArrowDown : ArrowRight;
  const label = value === "up" ? "Trending up" : value === "down" ? "Trending down" : "Holding steady";
  return <span className="inline-flex items-center gap-1 text-xs text-muted-foreground"><Icon className="h-3.5 w-3.5" aria-hidden="true" />{label}</span>;
}

function metricNumber(value: number | null | undefined, suffix = "") { return value == null ? "—" : `${value.toFixed(value % 1 ? 1 : 0)}${suffix}`; }

function History({ meetingId, meetingName }: { meetingId: string; meetingName: string }) {
  const history = trpc.pulse.settings.effectivenessHistory.useQuery({ meetingId });
  return <Dialog><DialogTrigger asChild><Button variant="ghost" className="min-h-11 px-2 text-left font-medium">{meetingName}</Button></DialogTrigger><DialogContent className="max-h-[90vh] max-w-4xl overflow-y-auto"><DialogHeader><DialogTitle>{meetingName} occurrence history</DialogTitle><DialogDescription>Neutral facts from completed meeting occurrences.</DialogDescription></DialogHeader>{history.isLoading ? <Skeleton className="h-80 w-full" /> : history.error ? <p className="text-sm text-destructive">{history.error.message}</p> : <div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="border-b border-border text-muted-foreground"><tr><th className="p-3 font-medium">Occurrence</th><th className="p-3 font-medium">Duration</th><th className="p-3 font-medium">To-dos</th><th className="p-3 font-medium">Issues resolved</th><th className="p-3 font-medium">Attendance</th><th className="p-3 font-medium">Rating</th></tr></thead><tbody>{(history.data?.occurrences ?? []).slice().reverse().map((row: any) => <tr key={row.id} className="border-b border-border"><td className="p-3">{formatEasternDateTime(row.occurredAt)}</td><td className="p-3">{row.durationActualMinutes ?? "—"} / {history.data?.meeting.scheduledMinutes} min</td><td className="p-3">{row.todosCompleted} completed / {row.todosCreated} created</td><td className="p-3">{row.issuesResolved}</td><td className="p-3">{row.attendeeIds.length} / {history.data?.meeting.memberCount}</td><td className="p-3">{row.rating ?? "—"}</td></tr>)}{!(history.data?.occurrences ?? []).length ? <tr><td colSpan={6} className="p-6 text-center text-muted-foreground">No completed occurrences are recorded yet.</td></tr> : null}</tbody></table></div>}</DialogContent></Dialog>;
}

export default function PulseMeetingEffectivenessPage() {
  const effectiveness = trpc.pulse.settings.effectiveness.useQuery();
  const [sort, setSort] = useState<"meeting" | "duration" | "todos" | "issues" | "attendance" | "rating">("meeting");
  const rows = useMemo(() => [...(effectiveness.data ?? [])].sort((left: any, right: any) => {
    const value = (row: any) => sort === "meeting" ? row.meeting.name : sort === "duration" ? row.duration.average ?? -1 : sort === "todos" ? row.todos.completed - row.todos.created : sort === "issues" ? row.issues.perOccurrence ?? -1 : sort === "attendance" ? row.attendance.average ?? -1 : row.rating.average ?? -1;
    return sort === "meeting" ? String(value(left)).localeCompare(String(value(right))) : Number(value(right)) - Number(value(left));
  }), [effectiveness.data, sort]);
  const header = (key: typeof sort, label: string) => <button type="button" className="min-h-11 text-left font-medium hover:underline" onClick={() => setSort(key)}>{label}{sort === key ? " · sorted" : ""}</button>;
  if (effectiveness.isLoading) return <main className="mx-auto max-w-7xl"><Skeleton className="h-96 w-full" /></main>;
  if (effectiveness.error) return <main className="mx-auto max-w-3xl"><Card><CardContent className="p-6"><p className="font-medium">This Pulse page is not available.</p><Link className="mt-3 inline-block underline" href="/pulse/settings">Return to Pulse settings</Link></CardContent></Card></main>;
  return <main className="mx-auto max-w-7xl space-y-6 pb-10"><header className="border-b border-border pb-5"><Button asChild variant="ghost" className="-ml-3 min-h-11"><Link href="/pulse/settings"><ArrowLeft className="mr-2 h-4 w-4" />Pulse settings</Link></Button><p className="mt-3 text-sm font-medium text-primary">Pulse</p><h1 className="mt-1 text-2xl font-semibold tracking-tight sm:text-3xl">Meeting effectiveness</h1><p className="mt-2 max-w-3xl text-base leading-6 text-muted-foreground">Trailing-eight occurrence facts to support a conversation. These are diagnostics, not scores, grades, or rankings.</p></header><Card><CardHeader><CardTitle>Meeting diagnostics</CardTitle><CardDescription>Click a column label to sort. Click a meeting name for occurrence-by-occurrence history.</CardDescription></CardHeader><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[980px] text-left text-sm"><thead className="border-y border-border bg-muted/40 text-muted-foreground"><tr><th className="px-4 py-3">{header("meeting", "Meeting")}</th><th className="px-4 py-3">{header("duration", "Average duration")}</th><th className="px-4 py-3">{header("todos", "To-dos completed vs. created")}</th><th className="px-4 py-3">{header("issues", "Issues resolved")}</th><th className="px-4 py-3">{header("attendance", "Attendance")}</th><th className="px-4 py-3">{header("rating", "Average rating")}</th></tr></thead><tbody>{rows.map((row: any) => <tr key={row.meeting.id} className="border-b border-border last:border-0"><td className="px-4 py-3"><History meetingId={row.meeting.id} meetingName={row.meeting.name} /><span className="block px-2 text-xs text-muted-foreground">{row.occurrenceCount} of 8 occurrences</span></td><td className="px-4 py-3"><p>{metricNumber(row.duration.average)} / {row.duration.scheduledMinutes} min</p><Trend value={row.duration.trend} /></td><td className="px-4 py-3"><p>{row.todos.completed} / {row.todos.created}</p><Trend value={row.todos.trend} /></td><td className="px-4 py-3"><p>{metricNumber(row.issues.perOccurrence)} per occurrence</p><Trend value={row.issues.trend} /></td><td className="px-4 py-3"><p>{metricNumber((row.attendance.average ?? 0) * 100, "%")}</p><Trend value={row.attendance.trend} /></td><td className="px-4 py-3"><p>{metricNumber(row.rating.average)} / 10</p><Trend value={row.rating.trend} /></td></tr>)}{!rows.length ? <tr><td colSpan={6} className="px-4 py-10 text-center text-muted-foreground">No active Pulse meetings are available.</td></tr> : null}</tbody></table></CardContent></Card></main>;
}
