import { useState } from "react";
import { Link } from "wouter";
import { Check } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";

function weekLabel(value:any){return new Date(value).toLocaleDateString(undefined,{month:"short",day:"numeric"});}
function Field({field,onSaved}:{field:any;onSaved:()=>void}){const [value,setValue]=useState(field.value??"");const [saved,setSaved]=useState(false);const save=trpc.pulse.personal.saveInput.useMutation({onSuccess:()=>{setSaved(true);onSaved();window.setTimeout(()=>setSaved(false),1300)}});const isNumber=field.kind==="number";return <label className="block border-t border-border py-3 first:border-t-0"><span className="flex items-start justify-between gap-3"><span><span className="block text-base font-medium">{field.label}</span><span className="mt-0.5 block text-sm text-muted-foreground">Feeds {field.meetingName}</span></span>{field.target!==undefined&&<span className="text-sm text-muted-foreground">Target {field.target??"—"}</span>}</span>{isNumber?<Input aria-label={field.label} className="mt-2 min-h-11 text-base" inputMode="numeric" type="number" value={value} onChange={e=>setValue(e.target.value)} onBlur={()=>{if(value!==""&&Number(value)!==field.value)save.mutate({key:field.key,value:Number(value),meetingId:field.meetingId})}} onKeyDown={e=>{if(e.key==="Enter")(e.currentTarget as HTMLInputElement).blur()}}/>:<textarea aria-label={field.label} className="mt-2 min-h-11 w-full rounded-md border border-input bg-background p-3 text-base" value={value} onChange={e=>setValue(e.target.value)} onBlur={()=>{if(value!==field.value&&value.trim())save.mutate({key:field.key,value,meetingId:field.meetingId})}} placeholder={field.key==="brief"?"A quick context note (optional)":"Share a useful update"}/>}<span aria-live="polite" className="mt-1 flex h-5 items-center text-xs text-emerald-700">{saved&&<><Check className="mr-1 h-3 w-3"/>Saved</>}</span></label>}
export default function PulseMyInputsPage(){const utils=trpc.useUtils();const {data,isLoading,error}=trpc.pulse.personal.inputs.useQuery();if(isLoading)return <div className="space-y-3"><Skeleton className="h-10 w-48"/><Skeleton className="h-64 w-full"/></div>;if(error||!data)return <p>Inputs are not available right now.</p>;const numbers=data.fields.filter((f:any)=>f.kind==="number");const text=data.fields.filter((f:any)=>f.kind==="text");return <main className="mx-auto max-w-2xl space-y-5"><header className="border-b border-border pb-5"><p className="text-sm font-medium text-primary">My week · Week of {weekLabel(data.weekOf)}</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">What do I need to put in this week?</h1><p className="mt-2 text-base text-muted-foreground">A few quick updates. Each one saves when you leave it.</p></header>{data.complete?<Card><CardContent className="p-5"><p className="font-medium">You’re done for this week.</p><Link className="mt-2 inline-block min-h-11 pt-2 text-sm font-medium underline" href="/pulse/work">See your work →</Link></CardContent></Card>:<><Card><CardContent className="p-4"><h2 className="text-base font-semibold">Submit your numbers <span className="font-normal text-muted-foreground">{numbers.filter((f:any)=>f.value===null).length} due</span></h2><div className="mt-2">{numbers.map((f:any)=><Field key={f.key} field={f} onSaved={()=>utils.pulse.personal.inputs.invalidate()}/>)}</div></CardContent></Card><Card><CardContent className="p-4"><h2 className="text-base font-semibold">Your quick update</h2><p className="mt-1 text-sm text-muted-foreground">A brief note helps your meetings start ready. No length limit.</p><div className="mt-2">{text.map((f:any)=><Field key={f.key} field={f} onSaved={()=>utils.pulse.personal.inputs.invalidate()}/>)}</div></CardContent></Card></>}</main>}
