import { useRef, useState } from "react";
import { Link, useLocation, useParams } from "wouter";
import { trpc } from "@/lib/trpc";
import PageHeader from "@/components/PageHeader";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { toast } from "sonner";
import { ArrowLeft, ArrowRightLeft, Building2, CalendarClock, CheckCircle2, DollarSign, FileText, Handshake, History, Loader2, MapPin, MessageSquare, Plus, Send, Upload, Wallet } from "lucide-react";

const TYPE_LABELS: Record<string, string> = { buyer: "Buyer", seller: "Seller", buyer_seller: "Buyer + Seller", other: "Other" };
const PAYMENT_LABELS: Record<string, string> = { not_yet_due: "Not Yet Due", due: "Due", invoiced: "Invoiced", processing: "Processing", paid: "Paid", disputed: "Disputed", written_off: "Written Off" };
function money(value: number | string | null | undefined) { return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(Number(value ?? 0)); }
function date(value: string | Date | null | undefined) { return value ? new Date(value).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" }) : "—"; }
function dateTime(value: string | Date | null | undefined) { return value ? new Date(value).toLocaleString(undefined, { month: "short", day: "numeric", year: "numeric", hour: "numeric", minute: "2-digit" }) : "—"; }
function categoryClass(category?: string | null) { return category === "closed" ? "bg-emerald-100 text-emerald-800 border-emerald-200" : category === "lost" ? "bg-rose-100 text-rose-800 border-rose-200" : category === "on_hold" ? "bg-amber-100 text-amber-800 border-amber-200" : "bg-sky-100 text-sky-800 border-sky-200"; }

export default function ReferralDetailPage() {
  const { id } = useParams<{ id: string }>();
  const [, navigate] = useLocation();
  const referralId = Number(id);
  const utils = trpc.useUtils();
  const { data, isLoading, refetch } = trpc.referrals.get.useQuery({ id: referralId });
  const { data: config } = trpc.referrals.config.useQuery();
  const [statusOpen, setStatusOpen] = useState(false);
  const [statusKey, setStatusKey] = useState("");
  const [statusNote, setStatusNote] = useState("");
  const [lostReason, setLostReason] = useState("");
  const [eventOpen, setEventOpen] = useState(false);
  const [eventType, setEventType] = useState<"note" | "referral_agent_update" | "call" | "email" | "follow_up" | "important_date">("referral_agent_update");
  const [eventTitle, setEventTitle] = useState("");
  const [eventBody, setEventBody] = useState("");
  const [eventFollowUp, setEventFollowUp] = useState("");
  const [convertOpen, setConvertOpen] = useState<"transaction" | "listing" | null>(null);
  const [transactionForm, setTransactionForm] = useState({ transactionType: "buyer", purchasePrice: "", contractDate: new Date().toISOString().slice(0, 10), closingDate: "", grossCommissionIncome: "", commissionRate: "", notes: "" });
  const [listingForm, setListingForm] = useState({ listPrice: "", listDate: new Date().toISOString().slice(0, 10), expirationDate: "", mlsNumber: "", notes: "" });
  const [reassignOpen, setReassignOpen] = useState(false);
  const [newAgentId, setNewAgentId] = useState("");
  const [reassignReason, setReassignReason] = useState("");
  const [newSplit, setNewSplit] = useState("");
  const fileInput = useRef<HTMLInputElement>(null);
  const [uploading, setUploading] = useState(false);

  const refresh = async () => { await refetch(); await utils.referrals.list.invalidate(); await utils.referrals.overview.invalidate(); await utils.referrals.listAgents.invalidate(); };
  const changeStatus = trpc.referrals.changeStatus.useMutation({ onSuccess: async () => { toast.success("Referral status updated"); setStatusOpen(false); setStatusNote(""); setLostReason(""); await refresh(); }, onError: (error) => toast.error(error.message) });
  const addEvent = trpc.referrals.addEvent.useMutation({ onSuccess: async () => { toast.success("Referral update added"); setEventOpen(false); setEventTitle(""); setEventBody(""); setEventFollowUp(""); await refresh(); }, onError: (error) => toast.error(error.message) });
  const convertTx = trpc.referrals.convertToTransaction.useMutation({ onSuccess: async ({ transactionId }) => { toast.success("Outside referral transaction created"); await refresh(); navigate(`/transactions/${transactionId}`); }, onError: (error) => toast.error(error.message) });
  const convertListing = trpc.referrals.convertToListing.useMutation({ onSuccess: async ({ listingId }) => { toast.success("Outside referral listing created"); await refresh(); navigate(`/listings/${listingId}`); }, onError: (error) => toast.error(error.message) });
  const reassign = trpc.referrals.reassign.useMutation({ onSuccess: ({ id }) => { toast.success("Referral reassigned; prior history has been preserved"); navigate(`/referrals/${id}`); }, onError: (error) => toast.error(error.message) });
  const updatePayment = trpc.referrals.updatePayment.useMutation({ onSuccess: async () => { toast.success("Referral payment updated"); await refresh(); }, onError: (error) => toast.error(error.message) });
  const attachDocument = trpc.referrals.attachDocument.useMutation({ onSuccess: async () => { toast.success("Referral document added"); await refresh(); }, onError: (error) => toast.error(error.message) });

  if (isLoading || !data) return <div className="flex h-64 items-center justify-center"><Loader2 className="h-6 w-6 animate-spin text-muted-foreground" /></div>;
  const referral = (data as any).referral;
  const contact = (data as any).contact;
  const referralAgent = (data as any).referralAgent;
  const status = (data as any).status;
  const statuses = ((config as any)?.statuses ?? []).filter((row: any) => row.isActive);
  const agents = ((config as any)?.agents ?? []).filter((agent: any) => agent.id !== referralAgent.id);
  const isSeller = ["seller", "buyer_seller"].includes(referral.referralType);

  async function uploadDocument(event: React.ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0];
    if (!file) return;
    if (file.size > 16 * 1024 * 1024) { toast.error("Documents must be 16 MB or smaller"); return; }
    setUploading(true);
    try {
      const form = new FormData(); form.append("file", file);
      const response = await fetch("/api/upload/referral-document", { method: "POST", body: form });
      const payload = await response.json();
      if (!response.ok) throw new Error(payload.error ?? "Upload failed");
      attachDocument.mutate({ referralId, referralAgentId: referralAgent.id, name: file.name, fileKey: payload.fileKey, fileUrl: payload.fileUrl, mimeType: file.type || null, fileSize: file.size, documentType: "other" });
    } catch (error: any) { toast.error(error.message ?? "Upload failed"); } finally { setUploading(false); event.target.value = ""; }
  }

  return <div className="space-y-6"><Button variant="ghost" size="sm" onClick={() => navigate("/referrals")}><ArrowLeft className="mr-1 h-4 w-4" />Back to referrals</Button><PageHeader title={`${contact.firstName} ${contact.lastName}`} subtitle={`Outbound ${TYPE_LABELS[referral.referralType].toLowerCase()} referral to ${referralAgent.name}`} actions={<div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => { setStatusKey(referral.statusKey); setStatusOpen(true); }}><CheckCircle2 className="mr-2 h-4 w-4" />Update status</Button><Button variant="outline" onClick={() => setEventOpen(true)}><MessageSquare className="mr-2 h-4 w-4" />Log update</Button><Button variant="outline" onClick={() => setReassignOpen(true)}><ArrowRightLeft className="mr-2 h-4 w-4" />Reassign</Button><Button onClick={() => setConvertOpen("transaction")}><Handshake className="mr-2 h-4 w-4" />Convert to transaction</Button>{isSeller && <Button variant="outline" onClick={() => setConvertOpen("listing")}><Building2 className="mr-2 h-4 w-4" />Convert to listing</Button>}</div>} />
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Card><CardContent className="p-4"><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Referral status</p><Badge variant="outline" className={`mt-2 ${categoryClass(referral.statusCategory)}`}>{status?.name ?? referral.statusKey}</Badge><p className="mt-2 text-xs text-muted-foreground">Sent {date(referral.referralSentAt)}</p></CardContent></Card><Card><CardContent className="p-4"><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Outside agent</p><Link href={`/referrals/agents/${referralAgent.id}`} className="mt-1 block font-semibold text-primary hover:underline">{referralAgent.name}</Link><p className="mt-1 text-xs text-muted-foreground">{referralAgent.brokerage ?? "Independent"}{!referralAgent.isActive ? " · Inactive" : ""}</p></CardContent></Card><Card><CardContent className="p-4"><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Savvy referral fee</p><p className="mt-1 text-2xl font-bold">{Number(referral.savvyReferralPct)}%</p><p className="mt-1 text-xs text-muted-foreground">Locked when this referral was created</p></CardContent></Card><Card><CardContent className="p-4"><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Follow-up health</p><p className="mt-1 text-2xl font-bold">{(data as any).daysSinceLastUpdate ?? 0}d</p><p className="mt-1 text-xs text-muted-foreground">Since last agent update · next {date(referral.nextFollowUpAt)}</p></CardContent></Card></div>
    <Card><CardContent className="grid gap-4 p-4 md:grid-cols-3"><div><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Client location interest</p><p className="mt-1 flex items-center gap-1.5 text-sm font-medium"><MapPin className="h-4 w-4 text-primary" />{referral.locationNotes ?? ([referral.market, referral.metro, referral.state].filter(Boolean).join(" · ") || "Not specified")}</p></div><div><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Last update received</p><p className="mt-1 text-sm font-medium">{dateTime(referral.lastUpdateReceivedAt)}</p><p className="mt-1 text-xs text-muted-foreground">Last agent contact: {dateTime(referral.lastReferralAgentContactAt)}</p></div><div><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Savvy contact</p><Link href={`/contacts/${contact.id}`} className="mt-1 block text-sm font-medium text-primary hover:underline">{contact.firstName} {contact.lastName}</Link><p className="mt-1 text-xs text-muted-foreground">{contact.email ?? contact.phone ?? "No contact method"}</p></div></CardContent></Card>
    <Tabs defaultValue="activity"><TabsList className="grid w-full grid-cols-5 sm:w-auto"><TabsTrigger value="activity">Activity</TabsTrigger><TabsTrigger value="deals">Listings & deals</TabsTrigger><TabsTrigger value="payments">Payments</TabsTrigger><TabsTrigger value="agreements">Agreements</TabsTrigger><TabsTrigger value="documents">Documents</TabsTrigger></TabsList>
      <TabsContent value="activity" className="space-y-3 pt-4">{(data as any).events.length === 0 ? <Card><CardContent className="p-8 text-center text-muted-foreground">No referral activity yet.</CardContent></Card> : (data as any).events.map((row: any) => <Card key={row.event.id}><CardContent className="p-4"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><Badge variant="outline" className="capitalize">{row.event.eventType.replace(/_/g, " ")}</Badge><p className="font-medium">{row.event.title}</p></div>{row.event.body && <p className="mt-2 whitespace-pre-wrap text-sm text-muted-foreground">{row.event.body}</p>}<p className="mt-2 text-xs text-muted-foreground">Entered by {row.user?.name ?? row.user?.email ?? "SavvyOS"}</p></div><p className="shrink-0 text-xs text-muted-foreground">{dateTime(row.event.occurredAt)}</p></div></CardContent></Card>)}</TabsContent>
      <TabsContent value="deals" className="space-y-3 pt-4"><div className="grid gap-3 lg:grid-cols-2"><Card><CardHeader><CardTitle className="text-base">Linked listings</CardTitle></CardHeader><CardContent className="space-y-2">{(data as any).listings.length ? (data as any).listings.map((row: any) => <Link key={row.listing.id} href={`/listings/${row.listing.id}`} className="block rounded-lg border p-3 transition-colors hover:bg-muted/40"><p className="font-medium">Listing #{row.listing.id}</p><p className="text-xs text-muted-foreground">{row.property?.address ?? "Property not set"} · {row.listing.listingStatus}</p></Link>) : <p className="text-sm text-muted-foreground">No listings linked. Convert when the outside agent signs a seller listing.</p>}</CardContent></Card><Card><CardHeader><CardTitle className="text-base">Linked transactions</CardTitle></CardHeader><CardContent className="space-y-2">{(data as any).transactions.length ? (data as any).transactions.map((row: any) => <Link key={row.transaction.id} href={`/transactions/${row.transaction.id}`} className="block rounded-lg border p-3 transition-colors hover:bg-muted/40"><p className="font-medium">{row.transaction.transactionNumber ?? `Transaction #${row.transaction.id}`}</p><p className="text-xs text-muted-foreground">{row.property?.address ?? "Property not set"} · {row.transaction.status} · {money(row.transaction.purchasePrice)}</p></Link>) : <p className="text-sm text-muted-foreground">No transactions linked. Convert when this client is under contract.</p>}</CardContent></Card></div></TabsContent>
      <TabsContent value="payments" className="space-y-3 pt-4">{(data as any).payments.length === 0 ? <Card><CardContent className="p-8 text-center text-muted-foreground">A payment receivable is created automatically when a linked outside-referral transaction is created or updated.</CardContent></Card> : (data as any).payments.map((row: any) => <Card key={row.payment.id}><CardContent className="flex flex-col gap-4 p-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="font-semibold">{row.transaction?.transactionNumber ?? "Referral payment"}</p><p className="mt-1 text-sm text-muted-foreground">GCI {money(row.payment.grossCommissionIncome)} × {Number(row.payment.savvyReferralPct)}% = <span className="font-semibold text-emerald-700">{money(row.payment.referralFeeOwed)} owed to Savvy</span></p><p className="mt-1 text-xs text-muted-foreground">Due {date(row.payment.dueAt)} · Paid {date(row.payment.paidAt)}</p></div><div className="flex items-center gap-2"><Select value={row.payment.paymentStatus} onValueChange={(paymentStatus: any) => updatePayment.mutate({ id: row.payment.id, data: { paymentStatus } })}><SelectTrigger className="w-40"><SelectValue /></SelectTrigger><SelectContent>{Object.entries(PAYMENT_LABELS).map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select>{row.payment.paymentStatus !== "paid" && <Button size="sm" onClick={() => updatePayment.mutate({ id: row.payment.id, data: { paymentStatus: "paid" } })}><CheckCircle2 className="mr-1.5 h-4 w-4" />Mark paid</Button>}</div></CardContent></Card>)}</TabsContent>
      <TabsContent value="agreements" className="space-y-3 pt-4">{(data as any).agreements.length === 0 ? <Card><CardContent className="p-8 text-center text-muted-foreground">No referral agreement has been recorded. Add one when the agreement is sent or executed.</CardContent></Card> : (data as any).agreements.map((agreement: any) => <Card key={agreement.id}><CardContent className="flex items-center justify-between gap-4 p-4"><div><p className="font-semibold">{agreement.title}</p><p className="mt-1 text-sm text-muted-foreground">{Number(agreement.savvyReferralPct ?? referral.savvyReferralPct)}% Savvy · {agreement.appliesTo.replace(/_/g, " ")}</p><p className="mt-1 text-xs text-muted-foreground">Effective {date(agreement.effectiveAt)} · Expires {date(agreement.expiresAt)} · Signed by {agreement.signedBy ?? "—"}</p></div><Badge variant="outline" className="capitalize">{agreement.status.replace(/_/g, " ")}</Badge></CardContent></Card>)}</TabsContent>
      <TabsContent value="documents" className="space-y-3 pt-4"><Card><CardContent className="flex items-center justify-between gap-4 p-4"><div><p className="font-medium">Referral documents</p><p className="text-xs text-muted-foreground">Upload executed agreements, closing statements, proof of payment, and important communications once and associate them to this referral.</p></div><input ref={fileInput} type="file" className="hidden" onChange={uploadDocument} accept=".pdf,.doc,.docx,.xls,.xlsx,.jpg,.jpeg,.png" /><Button variant="outline" onClick={() => fileInput.current?.click()} disabled={uploading || attachDocument.isPending}>{uploading || attachDocument.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Upload className="mr-2 h-4 w-4" />}Upload document</Button></CardContent></Card>{(data as any).documents.length === 0 ? <Card><CardContent className="p-8 text-center text-muted-foreground">No documents attached yet.</CardContent></Card> : (data as any).documents.map((document: any) => <a key={document.id} href={document.fileUrl} target="_blank" rel="noreferrer" className="block"><Card className="transition-colors hover:bg-muted/40"><CardContent className="flex items-center justify-between gap-4 p-4"><div className="flex items-center gap-3"><FileText className="h-5 w-5 text-primary" /><div><p className="font-medium">{document.name}</p><p className="text-xs text-muted-foreground">{document.documentType.replace(/_/g, " ")} · {date(document.createdAt)}</p></div></div><ArrowLeft className="h-4 w-4 rotate-180 text-muted-foreground" /></CardContent></Card></a>)}</TabsContent>
    </Tabs>
    <Dialog open={statusOpen} onOpenChange={setStatusOpen}><DialogContent><DialogHeader><DialogTitle>Update referral status</DialogTitle><DialogDescription>Referral status is independent from the Savvy contact, listing, and transaction statuses.</DialogDescription></DialogHeader><div className="space-y-3"><div className="space-y-1.5"><Label>Status</Label><Select value={statusKey} onValueChange={setStatusKey}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{statuses.map((option: any) => <SelectItem key={option.key} value={option.key}>{option.name}</SelectItem>)}</SelectContent></Select></div>{statusKey === "lost" && <div className="space-y-1.5"><Label>Lost reason *</Label><Textarea value={lostReason} onChange={(event) => setLostReason(event.target.value)} placeholder="Why this referral did not convert" /></div>}<div className="space-y-1.5"><Label>Update note</Label><Textarea value={statusNote} onChange={(event) => setStatusNote(event.target.value)} placeholder="What changed or what was reported by the outside agent?" /></div></div><DialogFooter><Button variant="outline" onClick={() => setStatusOpen(false)}>Cancel</Button><Button disabled={changeStatus.isPending} onClick={() => { if (statusKey === "lost" && !lostReason.trim()) return toast.error("Capture the lost reason"); changeStatus.mutate({ id: referralId, statusKey, note: statusNote || null, lostReason: lostReason || null }); }}>{changeStatus.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Save status</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={eventOpen} onOpenChange={setEventOpen}><DialogContent><DialogHeader><DialogTitle>Log referral update</DialogTitle><DialogDescription>Capture communications, outside-agent updates, follow-up attempts, and significant dates in the referral history.</DialogDescription></DialogHeader><div className="space-y-3"><div className="space-y-1.5"><Label>Update type</Label><Select value={eventType} onValueChange={(value: any) => setEventType(value)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="referral_agent_update">Update from referral agent</SelectItem><SelectItem value="call">Call</SelectItem><SelectItem value="email">Email</SelectItem><SelectItem value="follow_up">Follow-up attempt</SelectItem><SelectItem value="important_date">Important date</SelectItem><SelectItem value="note">Internal note</SelectItem></SelectContent></Select></div><div className="space-y-1.5"><Label>Title *</Label><Input value={eventTitle} onChange={(event) => setEventTitle(event.target.value)} placeholder="e.g., Agent confirmed client consultation" /></div><div className="space-y-1.5"><Label>Details</Label><Textarea value={eventBody} onChange={(event) => setEventBody(event.target.value)} /></div><div className="space-y-1.5"><Label>Next follow-up</Label><Input type="date" value={eventFollowUp} onChange={(event) => setEventFollowUp(event.target.value)} /></div></div><DialogFooter><Button variant="outline" onClick={() => setEventOpen(false)}>Cancel</Button><Button disabled={addEvent.isPending} onClick={() => { if (!eventTitle.trim()) return toast.error("Enter an update title"); addEvent.mutate({ referralId, eventType, title: eventTitle, body: eventBody || null, nextFollowUpAt: eventFollowUp || null, receivedFromReferralAgent: eventType === "referral_agent_update" }); }}><Send className="mr-2 h-4 w-4" />Save update</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={convertOpen === "transaction"} onOpenChange={(open) => !open && setConvertOpen(null)}><DialogContent><DialogHeader><DialogTitle>Convert to outside referral transaction</DialogTitle><DialogDescription>This creates a normal SavvyOS transaction while preserving this outside agent, fee percentage, client location context, contact, and referral record.</DialogDescription></DialogHeader><div className="grid gap-3 sm:grid-cols-2"><div className="space-y-1.5"><Label>Transaction type</Label><Select value={transactionForm.transactionType} onValueChange={(transactionType) => setTransactionForm({ ...transactionForm, transactionType })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="buyer">Buyer</SelectItem><SelectItem value="seller">Seller</SelectItem><SelectItem value="dual">Dual</SelectItem></SelectContent></Select></div><div className="space-y-1.5"><Label>Purchase price</Label><Input type="number" value={transactionForm.purchasePrice} onChange={(event) => setTransactionForm({ ...transactionForm, purchasePrice: event.target.value })} /></div><div className="space-y-1.5"><Label>Contract date</Label><Input type="date" value={transactionForm.contractDate} onChange={(event) => setTransactionForm({ ...transactionForm, contractDate: event.target.value })} /></div><div className="space-y-1.5"><Label>Expected close</Label><Input type="date" value={transactionForm.closingDate} onChange={(event) => setTransactionForm({ ...transactionForm, closingDate: event.target.value })} /></div><div className="space-y-1.5"><Label>GCI</Label><Input type="number" value={transactionForm.grossCommissionIncome} onChange={(event) => setTransactionForm({ ...transactionForm, grossCommissionIncome: event.target.value })} /></div><div className="space-y-1.5"><Label>Commission rate</Label><Input type="number" value={transactionForm.commissionRate} onChange={(event) => setTransactionForm({ ...transactionForm, commissionRate: event.target.value })} /></div><div className="space-y-1.5 sm:col-span-2"><Label>Notes</Label><Textarea value={transactionForm.notes} onChange={(event) => setTransactionForm({ ...transactionForm, notes: event.target.value })} /></div></div><DialogFooter><Button variant="outline" onClick={() => setConvertOpen(null)}>Cancel</Button><Button disabled={convertTx.isPending} onClick={() => convertTx.mutate({ referralId, transactionType: transactionForm.transactionType as any, purchasePrice: transactionForm.purchasePrice || null, contractDate: transactionForm.contractDate || null, closingDate: transactionForm.closingDate || null, grossCommissionIncome: transactionForm.grossCommissionIncome || null, commissionRate: transactionForm.commissionRate || null, notes: transactionForm.notes || null })}>{convertTx.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Create transaction</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={convertOpen === "listing"} onOpenChange={(open) => !open && setConvertOpen(null)}><DialogContent><DialogHeader><DialogTitle>Convert to outside referral listing</DialogTitle><DialogDescription>This creates a SavvyOS listing attributed to the outside agent and this referral agreement.</DialogDescription></DialogHeader><div className="grid gap-3 sm:grid-cols-2"><div className="space-y-1.5"><Label>List price</Label><Input type="number" value={listingForm.listPrice} onChange={(event) => setListingForm({ ...listingForm, listPrice: event.target.value })} /></div><div className="space-y-1.5"><Label>List date</Label><Input type="date" value={listingForm.listDate} onChange={(event) => setListingForm({ ...listingForm, listDate: event.target.value })} /></div><div className="space-y-1.5"><Label>Expiration date</Label><Input type="date" value={listingForm.expirationDate} onChange={(event) => setListingForm({ ...listingForm, expirationDate: event.target.value })} /></div><div className="space-y-1.5"><Label>MLS number</Label><Input value={listingForm.mlsNumber} onChange={(event) => setListingForm({ ...listingForm, mlsNumber: event.target.value })} /></div><div className="space-y-1.5 sm:col-span-2"><Label>Notes</Label><Textarea value={listingForm.notes} onChange={(event) => setListingForm({ ...listingForm, notes: event.target.value })} /></div></div><DialogFooter><Button variant="outline" onClick={() => setConvertOpen(null)}>Cancel</Button><Button disabled={convertListing.isPending} onClick={() => convertListing.mutate({ referralId, listPrice: listingForm.listPrice || null, listDate: listingForm.listDate || null, expirationDate: listingForm.expirationDate || null, mlsNumber: listingForm.mlsNumber || null, notes: listingForm.notes || null })}>{convertListing.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Create listing</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={reassignOpen} onOpenChange={setReassignOpen}><DialogContent><DialogHeader><DialogTitle>Reassign this referral</DialogTitle><DialogDescription>The existing referral stays intact as the historical record; SavvyOS creates a new referral under the replacement agent.</DialogDescription></DialogHeader><div className="space-y-3"><div className="space-y-1.5"><Label>Replacement referral agent *</Label><Select value={newAgentId} onValueChange={setNewAgentId}><SelectTrigger><SelectValue placeholder="Select an agent" /></SelectTrigger><SelectContent>{agents.map((agent: any) => <SelectItem key={agent.id} value={String(agent.id)}>{agent.name}{agent.brokerage ? ` · ${agent.brokerage}` : ""}</SelectItem>)}</SelectContent></Select></div><div className="space-y-1.5"><Label>New Savvy referral percentage</Label><Input type="number" value={newSplit} onChange={(event) => setNewSplit(event.target.value)} placeholder={String(referral.savvyReferralPct)} /></div><div className="space-y-1.5"><Label>Reason *</Label><Textarea value={reassignReason} onChange={(event) => setReassignReason(event.target.value)} placeholder="Why did the original placement not work?" /></div></div><DialogFooter><Button variant="outline" onClick={() => setReassignOpen(false)}>Cancel</Button><Button disabled={reassign.isPending} onClick={() => { if (!newAgentId || !reassignReason.trim()) return toast.error("Select an agent and enter the reason"); reassign.mutate({ referralId, newReferralAgentId: Number(newAgentId), savvyReferralPct: newSplit || null, reason: reassignReason }); }}>{reassign.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Reassign referral</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
