/**
 * DDL for the MLS Properties tables, generated from drizzle/mlsSchema.ts via a
 * local MySQL 8.4 push and kept identical to drizzle/20260929_mls_properties.sql.
 * Every statement is CREATE TABLE IF NOT EXISTS, so applying it is additive and
 * safe to repeat.
 */
export const MLS_TABLE_DDL: ReadonlyArray<{ table: string; sql: string }> = [
  {
    table: "mls_sources",
    sql: `CREATE TABLE IF NOT EXISTS \`mls_sources\` (
  \`id\` int NOT NULL AUTO_INCREMENT,
  \`code\` varchar(64) NOT NULL,
  \`name\` varchar(255) NOT NULL,
  \`shortName\` varchar(64) NOT NULL,
  \`territory\` varchar(512) DEFAULT NULL,
  \`providerRoute\` enum('mls_grid','trestle','spark','reso_web_api','custom','unresolved') NOT NULL,
  \`onboardingStatus\` enum('planned','conditional','applied','approved','live','paused','unresolved') NOT NULL DEFAULT 'planned',
  \`routeNote\` text,
  \`originatingSystemName\` varchar(64) DEFAULT NULL,
  \`keyPrefix\` varchar(16) DEFAULT NULL,
  \`websiteUrl\` varchar(512) DEFAULT NULL,
  \`compliance\` json DEFAULT NULL,
  \`sortOrder\` int NOT NULL DEFAULT '0',
  \`createdAt\` timestamp NOT NULL DEFAULT (now()),
  \`updatedAt\` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`mls_sources_code_uq\` (\`code\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  },
  {
    table: "mls_feeds",
    sql: `CREATE TABLE IF NOT EXISTS \`mls_feeds\` (
  \`id\` int NOT NULL AUTO_INCREMENT,
  \`sourceId\` int NOT NULL,
  \`name\` varchar(255) NOT NULL,
  \`provider\` enum('mls_grid','trestle','spark','reso_web_api','custom') NOT NULL,
  \`feedType\` enum('idx','idx_plus','vow','bbo','participant','other') NOT NULL DEFAULT 'idx',
  \`baseUrl\` varchar(512) NOT NULL,
  \`tokenUrl\` varchar(512) DEFAULT NULL,
  \`originatingSystemName\` varchar(64) DEFAULT NULL,
  \`keyPrefix\` varchar(16) DEFAULT NULL,
  \`credentialRef\` varchar(64) NOT NULL,
  \`resources\` json DEFAULT NULL,
  \`options\` json DEFAULT NULL,
  \`enabled\` tinyint(1) NOT NULL DEFAULT '0',
  \`syncIntervalMinutes\` int NOT NULL DEFAULT '15',
  \`reconcileIntervalHours\` int NOT NULL DEFAULT '24',
  \`maxStalenessHours\` int NOT NULL DEFAULT '12',
  \`mediaPolicy\` enum('all','active_all_else_primary','primary_only','none') NOT NULL DEFAULT 'active_all_else_primary',
  \`retentionPolicy\` enum('purge','retain_history') NOT NULL DEFAULT 'purge',
  \`status\` enum('idle','running','error','suspended') NOT NULL DEFAULT 'idle',
  \`lastError\` text,
  \`lastRunStartedAt\` datetime DEFAULT NULL,
  \`lastRunFinishedAt\` datetime DEFAULT NULL,
  \`lastSuccessAt\` datetime DEFAULT NULL,
  \`lastReconcileAt\` datetime DEFAULT NULL,
  \`lastMetadataAt\` datetime DEFAULT NULL,
  \`initialImportCompletedAt\` datetime DEFAULT NULL,
  \`syncRequestedAt\` datetime DEFAULT NULL,
  \`reconcileRequestedAt\` datetime DEFAULT NULL,
  \`leaseOwner\` varchar(160) DEFAULT NULL,
  \`leaseExpiresAt\` datetime DEFAULT NULL,
  \`createdById\` int DEFAULT NULL,
  \`createdAt\` timestamp NOT NULL DEFAULT (now()),
  \`updatedAt\` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`mls_feeds_source_provider_type_uq\` (\`sourceId\`,\`provider\`,\`feedType\`),
  KEY \`mls_feeds_enabled_idx\` (\`enabled\`,\`provider\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  },
  {
    table: "mls_sync_cursors",
    sql: `CREATE TABLE IF NOT EXISTS \`mls_sync_cursors\` (
  \`id\` int NOT NULL AUTO_INCREMENT,
  \`feedId\` int NOT NULL,
  \`resource\` varchar(32) NOT NULL,
  \`phase\` enum('initial','incremental') NOT NULL DEFAULT 'initial',
  \`highWaterMark\` varchar(40) DEFAULT NULL,
  \`resumeToken\` text,
  \`sweepStartedAt\` datetime DEFAULT NULL,
  \`recordsSeen\` bigint NOT NULL DEFAULT '0',
  \`lastSuccessAt\` datetime DEFAULT NULL,
  \`updatedAt\` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`mls_sync_cursors_feed_resource_uq\` (\`feedId\`,\`resource\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  },
  {
    table: "mls_sync_runs",
    sql: `CREATE TABLE IF NOT EXISTS \`mls_sync_runs\` (
  \`id\` bigint unsigned NOT NULL AUTO_INCREMENT,
  \`feedId\` int NOT NULL,
  \`kind\` enum('initial','incremental','reconcile','metadata','media') NOT NULL,
  \`resource\` varchar(32) DEFAULT NULL,
  \`status\` enum('running','succeeded','failed','aborted') NOT NULL DEFAULT 'running',
  \`startedAt\` datetime NOT NULL,
  \`finishedAt\` datetime DEFAULT NULL,
  \`requests\` int NOT NULL DEFAULT '0',
  \`bytes\` bigint NOT NULL DEFAULT '0',
  \`received\` int NOT NULL DEFAULT '0',
  \`upserted\` int NOT NULL DEFAULT '0',
  \`unchanged\` int NOT NULL DEFAULT '0',
  \`deleted\` int NOT NULL DEFAULT '0',
  \`mediaQueued\` int NOT NULL DEFAULT '0',
  \`error\` text,
  \`detail\` json DEFAULT NULL,
  PRIMARY KEY (\`id\`),
  KEY \`mls_sync_runs_feed_started_idx\` (\`feedId\`,\`startedAt\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  },
  {
    table: "mls_raw_records",
    sql: `CREATE TABLE IF NOT EXISTS \`mls_raw_records\` (
  \`id\` bigint unsigned NOT NULL AUTO_INCREMENT,
  \`feedId\` int NOT NULL,
  \`resource\` varchar(32) NOT NULL,
  \`providerKey\` varchar(160) NOT NULL,
  \`payloadGzip\` mediumblob NOT NULL,
  \`payloadHash\` varchar(64) NOT NULL,
  \`payloadBytes\` int NOT NULL,
  \`sourceModifiedAt\` datetime(3) DEFAULT NULL,
  \`receivedAt\` datetime NOT NULL,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`mls_raw_records_feed_resource_key_uq\` (\`feedId\`,\`resource\`,\`providerKey\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  },
  {
    table: "mls_properties",
    sql: `CREATE TABLE IF NOT EXISTS \`mls_properties\` (
  \`id\` bigint unsigned NOT NULL AUTO_INCREMENT,
  \`propertyKey\` varchar(64) NOT NULL,
  \`identitySource\` enum('address','parcel','listing') NOT NULL,
  \`universalPropertyId\` varchar(128) DEFAULT NULL,
  \`parcelNumber\` varchar(128) DEFAULT NULL,
  \`streetNumber\` varchar(32) DEFAULT NULL,
  \`streetName\` varchar(128) DEFAULT NULL,
  \`unitNumber\` varchar(32) DEFAULT NULL,
  \`unparsedAddress\` varchar(300) DEFAULT NULL,
  \`city\` varchar(128) DEFAULT NULL,
  \`stateOrProvince\` varchar(32) DEFAULT NULL,
  \`postalCode\` varchar(16) DEFAULT NULL,
  \`countyOrParish\` varchar(128) DEFAULT NULL,
  \`country\` varchar(8) DEFAULT NULL,
  \`latitude\` decimal(10,7) DEFAULT NULL,
  \`longitude\` decimal(11,7) DEFAULT NULL,
  \`propertyType\` varchar(48) DEFAULT NULL,
  \`propertySubType\` varchar(96) DEFAULT NULL,
  \`yearBuilt\` int DEFAULT NULL,
  \`bedroomsTotal\` int DEFAULT NULL,
  \`bathroomsTotal\` decimal(5,2) DEFAULT NULL,
  \`livingArea\` decimal(12,2) DEFAULT NULL,
  \`lotSizeAcres\` decimal(12,4) DEFAULT NULL,
  \`latestListingId\` bigint unsigned DEFAULT NULL,
  \`latestStatus\` varchar(32) DEFAULT NULL,
  \`latestListPrice\` decimal(14,2) DEFAULT NULL,
  \`lastClosePrice\` decimal(14,2) DEFAULT NULL,
  \`lastCloseDate\` date DEFAULT NULL,
  \`listingCount\` int NOT NULL DEFAULT '0',
  \`createdAt\` timestamp NOT NULL DEFAULT (now()),
  \`updatedAt\` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`mls_properties_key_uq\` (\`propertyKey\`),
  KEY \`mls_properties_postal_idx\` (\`postalCode\`),
  KEY \`mls_properties_geo_idx\` (\`latitude\`,\`longitude\`),
  KEY \`mls_properties_parcel_idx\` (\`parcelNumber\`,\`stateOrProvince\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  },
  {
    table: "mls_property_insights",
    sql: `CREATE TABLE IF NOT EXISTS \`mls_property_insights\` (
  \`id\` bigint unsigned NOT NULL AUTO_INCREMENT,
  \`propertyId\` bigint unsigned NOT NULL,
  \`strAllowed\` enum('yes','no','restricted','unknown') NOT NULL DEFAULT 'unknown',
  \`strRestrictionStatus\` varchar(64) DEFAULT NULL,
  \`permitRequired\` tinyint(1) DEFAULT NULL,
  \`permitType\` varchar(128) DEFAULT NULL,
  \`hoaStrRestriction\` varchar(255) DEFAULT NULL,
  \`minimumRentalDays\` int DEFAULT NULL,
  \`occupancyLimit\` int DEFAULT NULL,
  \`rentalIncomeClaimed\` decimal(14,2) DEFAULT NULL,
  \`projectedStrRevenue\` decimal(14,2) DEFAULT NULL,
  \`airbnbMatch\` json DEFAULT NULL,
  \`marketId\` int DEFAULT NULL,
  \`investmentScore\` decimal(6,2) DEFAULT NULL,
  \`buyBoxMatches\` json DEFAULT NULL,
  \`provenance\` json DEFAULT NULL,
  \`createdAt\` timestamp NOT NULL DEFAULT (now()),
  \`updatedAt\` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`mls_property_insights_property_uq\` (\`propertyId\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  },
  {
    table: "mls_listings",
    sql: `CREATE TABLE IF NOT EXISTS \`mls_listings\` (
  \`id\` bigint unsigned NOT NULL AUTO_INCREMENT,
  \`propertyId\` bigint unsigned NOT NULL,
  \`sourceId\` int NOT NULL,
  \`feedId\` int NOT NULL,
  \`listingNumber\` varchar(64) NOT NULL,
  \`listingKey\` varchar(128) NOT NULL,
  \`providerListingKey\` varchar(160) NOT NULL,
  \`standardStatus\` varchar(32) NOT NULL,
  \`mlsStatus\` varchar(64) DEFAULT NULL,
  \`propertyType\` varchar(48) DEFAULT NULL,
  \`propertySubType\` varchar(96) DEFAULT NULL,
  \`listPrice\` decimal(14,2) DEFAULT NULL,
  \`originalListPrice\` decimal(14,2) DEFAULT NULL,
  \`previousListPrice\` decimal(14,2) DEFAULT NULL,
  \`closePrice\` decimal(14,2) DEFAULT NULL,
  \`listingContractDate\` date DEFAULT NULL,
  \`onMarketDate\` date DEFAULT NULL,
  \`purchaseContractDate\` date DEFAULT NULL,
  \`offMarketDate\` date DEFAULT NULL,
  \`closeDate\` date DEFAULT NULL,
  \`statusChangeAt\` datetime(3) DEFAULT NULL,
  \`priceChangeAt\` datetime(3) DEFAULT NULL,
  \`originalEntryAt\` datetime(3) DEFAULT NULL,
  \`daysOnMarket\` int DEFAULT NULL,
  \`cumulativeDaysOnMarket\` int DEFAULT NULL,
  \`bedroomsTotal\` int DEFAULT NULL,
  \`bathroomsTotalInteger\` int DEFAULT NULL,
  \`bathroomsFull\` int DEFAULT NULL,
  \`bathroomsHalf\` int DEFAULT NULL,
  \`bathroomsTotal\` decimal(5,2) DEFAULT NULL,
  \`livingArea\` decimal(12,2) DEFAULT NULL,
  \`livingAreaUnits\` varchar(16) DEFAULT NULL,
  \`aboveGradeFinishedArea\` decimal(12,2) DEFAULT NULL,
  \`belowGradeFinishedArea\` decimal(12,2) DEFAULT NULL,
  \`buildingAreaTotal\` decimal(12,2) DEFAULT NULL,
  \`lotSizeAcres\` decimal(12,4) DEFAULT NULL,
  \`lotSizeSquareFeet\` decimal(14,2) DEFAULT NULL,
  \`yearBuilt\` int DEFAULT NULL,
  \`storiesTotal\` int DEFAULT NULL,
  \`garageSpaces\` decimal(6,1) DEFAULT NULL,
  \`parkingTotal\` decimal(6,1) DEFAULT NULL,
  \`poolPrivateYN\` tinyint(1) DEFAULT NULL,
  \`waterfrontYN\` tinyint(1) DEFAULT NULL,
  \`viewYN\` tinyint(1) DEFAULT NULL,
  \`fireplaceYN\` tinyint(1) DEFAULT NULL,
  \`newConstructionYN\` tinyint(1) DEFAULT NULL,
  \`furnished\` varchar(64) DEFAULT NULL,
  \`associationYN\` tinyint(1) DEFAULT NULL,
  \`associationName\` varchar(191) DEFAULT NULL,
  \`associationFee\` decimal(12,2) DEFAULT NULL,
  \`associationFeeFrequency\` varchar(32) DEFAULT NULL,
  \`taxAnnualAmount\` decimal(12,2) DEFAULT NULL,
  \`taxYear\` int DEFAULT NULL,
  \`taxAssessedValue\` decimal(14,2) DEFAULT NULL,
  \`parcelNumber\` varchar(128) DEFAULT NULL,
  \`zoning\` varchar(128) DEFAULT NULL,
  \`subdivisionName\` varchar(191) DEFAULT NULL,
  \`mlsAreaMajor\` varchar(128) DEFAULT NULL,
  \`elementarySchool\` varchar(128) DEFAULT NULL,
  \`middleSchool\` varchar(128) DEFAULT NULL,
  \`highSchool\` varchar(128) DEFAULT NULL,
  \`unparsedAddress\` varchar(300) DEFAULT NULL,
  \`streetNumber\` varchar(32) DEFAULT NULL,
  \`streetName\` varchar(128) DEFAULT NULL,
  \`unitNumber\` varchar(32) DEFAULT NULL,
  \`city\` varchar(128) DEFAULT NULL,
  \`stateOrProvince\` varchar(32) DEFAULT NULL,
  \`postalCode\` varchar(16) DEFAULT NULL,
  \`countyOrParish\` varchar(128) DEFAULT NULL,
  \`latitude\` decimal(10,7) DEFAULT NULL,
  \`longitude\` decimal(11,7) DEFAULT NULL,
  \`publicRemarks\` text,
  \`directions\` text,
  \`virtualTourUrl\` varchar(1024) DEFAULT NULL,
  \`listAgentKey\` varchar(128) DEFAULT NULL,
  \`listAgentMlsId\` varchar(64) DEFAULT NULL,
  \`listAgentFullName\` varchar(191) DEFAULT NULL,
  \`listAgentPhone\` varchar(64) DEFAULT NULL,
  \`listAgentEmail\` varchar(191) DEFAULT NULL,
  \`listOfficeKey\` varchar(128) DEFAULT NULL,
  \`listOfficeMlsId\` varchar(64) DEFAULT NULL,
  \`listOfficeName\` varchar(191) DEFAULT NULL,
  \`listOfficePhone\` varchar(64) DEFAULT NULL,
  \`coListAgentFullName\` varchar(191) DEFAULT NULL,
  \`coListOfficeName\` varchar(191) DEFAULT NULL,
  \`buyerAgentKey\` varchar(128) DEFAULT NULL,
  \`buyerAgentFullName\` varchar(191) DEFAULT NULL,
  \`buyerOfficeKey\` varchar(128) DEFAULT NULL,
  \`buyerOfficeName\` varchar(191) DEFAULT NULL,
  \`photosCount\` int DEFAULT NULL,
  \`photosChangeAt\` datetime(3) DEFAULT NULL,
  \`primaryPhotoUrl\` varchar(1024) DEFAULT NULL,
  \`internetEntireListingDisplayYN\` tinyint(1) DEFAULT NULL,
  \`internetAddressDisplayYN\` tinyint(1) DEFAULT NULL,
  \`internetAvmDisplayYN\` tinyint(1) DEFAULT NULL,
  \`internetConsumerCommentYN\` tinyint(1) DEFAULT NULL,
  \`idxParticipationYN\` tinyint(1) DEFAULT NULL,
  \`permittedUses\` json DEFAULT NULL,
  \`features\` json DEFAULT NULL,
  \`rooms\` json DEFAULT NULL,
  \`units\` json DEFAULT NULL,
  \`localFields\` json DEFAULT NULL,
  \`fieldProvenance\` json DEFAULT NULL,
  \`mappingVersion\` int NOT NULL DEFAULT '1',
  \`sourceModifiedAt\` datetime(3) DEFAULT NULL,
  \`originatingModifiedAt\` datetime(3) DEFAULT NULL,
  \`payloadHash\` varchar(64) DEFAULT NULL,
  \`firstSeenAt\` datetime NOT NULL,
  \`lastSyncedAt\` datetime NOT NULL,
  \`removedFromFeedAt\` datetime DEFAULT NULL,
  \`removalReason\` varchar(64) DEFAULT NULL,
  \`createdAt\` timestamp NOT NULL DEFAULT (now()),
  \`updatedAt\` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`),
  KEY \`mls_listings_source_number_idx\` (\`sourceId\`,\`listingNumber\`),
  UNIQUE KEY \`mls_listings_feed_provider_key_uq\` (\`feedId\`,\`providerListingKey\`),
  KEY \`mls_listings_property_idx\` (\`propertyId\`),
  KEY \`mls_listings_status_geo_idx\` (\`standardStatus\`,\`latitude\`,\`longitude\`),
  KEY \`mls_listings_source_status_price_idx\` (\`sourceId\`,\`standardStatus\`,\`listPrice\`),
  KEY \`mls_listings_status_price_idx\` (\`standardStatus\`,\`listPrice\`),
  KEY \`mls_listings_status_entry_idx\` (\`standardStatus\`,\`originalEntryAt\`),
  KEY \`mls_listings_postal_idx\` (\`postalCode\`),
  KEY \`mls_listings_city_idx\` (\`city\`,\`stateOrProvince\`),
  KEY \`mls_listings_modified_idx\` (\`sourceModifiedAt\`),
  KEY \`mls_listings_close_idx\` (\`closeDate\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  },
  {
    table: "mls_listing_history",
    sql: `CREATE TABLE IF NOT EXISTS \`mls_listing_history\` (
  \`id\` bigint unsigned NOT NULL AUTO_INCREMENT,
  \`listingId\` bigint unsigned NOT NULL,
  \`propertyId\` bigint unsigned NOT NULL,
  \`sourceId\` int NOT NULL,
  \`eventType\` enum('listed','relisted','status_change','price_change','back_on_market','pending','closed','withdrawn','expired','canceled','removed_from_feed') NOT NULL,
  \`fromStatus\` varchar(32) DEFAULT NULL,
  \`toStatus\` varchar(32) DEFAULT NULL,
  \`fromPrice\` decimal(14,2) DEFAULT NULL,
  \`toPrice\` decimal(14,2) DEFAULT NULL,
  \`eventAt\` datetime(3) NOT NULL,
  \`detectedAt\` datetime NOT NULL,
  \`detail\` json DEFAULT NULL,
  PRIMARY KEY (\`id\`),
  KEY \`mls_listing_history_listing_idx\` (\`listingId\`,\`eventAt\`),
  KEY \`mls_listing_history_property_idx\` (\`propertyId\`,\`eventAt\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  },
  {
    table: "mls_media",
    sql: `CREATE TABLE IF NOT EXISTS \`mls_media\` (
  \`id\` bigint unsigned NOT NULL AUTO_INCREMENT,
  \`feedId\` int NOT NULL,
  \`listingId\` bigint unsigned DEFAULT NULL,
  \`resourceKey\` varchar(160) NOT NULL,
  \`mediaKey\` varchar(191) NOT NULL,
  \`sortOrder\` int NOT NULL DEFAULT '0',
  \`category\` varchar(32) DEFAULT NULL,
  \`mimeType\` varchar(64) DEFAULT NULL,
  \`caption\` varchar(512) DEFAULT NULL,
  \`isPrimary\` tinyint(1) NOT NULL DEFAULT '0',
  \`sourceModifiedAt\` datetime(3) DEFAULT NULL,
  \`sourceUrl\` text,
  \`sourceUrlExpiresAt\` datetime DEFAULT NULL,
  \`status\` enum('pending','downloading','stored','skipped','expired','failed','delete_pending') NOT NULL DEFAULT 'pending',
  \`priority\` int NOT NULL DEFAULT '100',
  \`attempts\` int NOT NULL DEFAULT '0',
  \`lastError\` varchar(512) DEFAULT NULL,
  \`nextAttemptAt\` datetime DEFAULT NULL,
  \`claimedBy\` varchar(160) DEFAULT NULL,
  \`s3Key\` varchar(512) DEFAULT NULL,
  \`url\` varchar(1024) DEFAULT NULL,
  \`bytes\` int DEFAULT NULL,
  \`storedAt\` datetime DEFAULT NULL,
  \`createdAt\` timestamp NOT NULL DEFAULT (now()),
  \`updatedAt\` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`mls_media_feed_key_uq\` (\`feedId\`,\`mediaKey\`),
  KEY \`mls_media_queue_idx\` (\`status\`,\`priority\`,\`nextAttemptAt\`),
  KEY \`mls_media_listing_idx\` (\`listingId\`,\`sortOrder\`),
  KEY \`mls_media_resource_idx\` (\`feedId\`,\`resourceKey\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  },
  {
    table: "mls_members",
    sql: `CREATE TABLE IF NOT EXISTS \`mls_members\` (
  \`id\` bigint unsigned NOT NULL AUTO_INCREMENT,
  \`sourceId\` int NOT NULL,
  \`feedId\` int NOT NULL,
  \`memberKey\` varchar(160) NOT NULL,
  \`memberMlsId\` varchar(64) DEFAULT NULL,
  \`fullName\` varchar(191) DEFAULT NULL,
  \`email\` varchar(191) DEFAULT NULL,
  \`phone\` varchar(64) DEFAULT NULL,
  \`officeKey\` varchar(160) DEFAULT NULL,
  \`officeMlsId\` varchar(64) DEFAULT NULL,
  \`officeName\` varchar(191) DEFAULT NULL,
  \`memberStatus\` varchar(32) DEFAULT NULL,
  \`stateLicense\` varchar(64) DEFAULT NULL,
  \`localFields\` json DEFAULT NULL,
  \`sourceModifiedAt\` datetime(3) DEFAULT NULL,
  \`lastSyncedAt\` datetime NOT NULL,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`mls_members_feed_key_uq\` (\`feedId\`,\`memberKey\`),
  KEY \`mls_members_source_mlsid_idx\` (\`sourceId\`,\`memberMlsId\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  },
  {
    table: "mls_offices",
    sql: `CREATE TABLE IF NOT EXISTS \`mls_offices\` (
  \`id\` bigint unsigned NOT NULL AUTO_INCREMENT,
  \`sourceId\` int NOT NULL,
  \`feedId\` int NOT NULL,
  \`officeKey\` varchar(160) NOT NULL,
  \`officeMlsId\` varchar(64) DEFAULT NULL,
  \`officeName\` varchar(191) DEFAULT NULL,
  \`phone\` varchar(64) DEFAULT NULL,
  \`email\` varchar(191) DEFAULT NULL,
  \`city\` varchar(128) DEFAULT NULL,
  \`stateOrProvince\` varchar(32) DEFAULT NULL,
  \`officeStatus\` varchar(32) DEFAULT NULL,
  \`localFields\` json DEFAULT NULL,
  \`sourceModifiedAt\` datetime(3) DEFAULT NULL,
  \`lastSyncedAt\` datetime NOT NULL,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`mls_offices_feed_key_uq\` (\`feedId\`,\`officeKey\`),
  KEY \`mls_offices_source_mlsid_idx\` (\`sourceId\`,\`officeMlsId\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  },
  {
    table: "mls_open_houses",
    sql: `CREATE TABLE IF NOT EXISTS \`mls_open_houses\` (
  \`id\` bigint unsigned NOT NULL AUTO_INCREMENT,
  \`feedId\` int NOT NULL,
  \`listingId\` bigint unsigned DEFAULT NULL,
  \`openHouseKey\` varchar(160) NOT NULL,
  \`providerListingKey\` varchar(160) DEFAULT NULL,
  \`startAt\` datetime DEFAULT NULL,
  \`endAt\` datetime DEFAULT NULL,
  \`openHouseDate\` date DEFAULT NULL,
  \`openHouseType\` varchar(48) DEFAULT NULL,
  \`openHouseStatus\` varchar(32) DEFAULT NULL,
  \`remarks\` text,
  \`sourceModifiedAt\` datetime(3) DEFAULT NULL,
  \`lastSyncedAt\` datetime NOT NULL,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`mls_open_houses_feed_key_uq\` (\`feedId\`,\`openHouseKey\`),
  KEY \`mls_open_houses_listing_idx\` (\`listingId\`,\`startAt\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  },
  {
    table: "mls_field_mappings",
    sql: `CREATE TABLE IF NOT EXISTS \`mls_field_mappings\` (
  \`id\` int NOT NULL AUTO_INCREMENT,
  \`sourceId\` int DEFAULT NULL,
  \`provider\` varchar(32) DEFAULT NULL,
  \`resource\` varchar(32) NOT NULL DEFAULT 'Property',
  \`sourceField\` varchar(191) NOT NULL,
  \`resoField\` varchar(191) DEFAULT NULL,
  \`target\` varchar(191) NOT NULL,
  \`transform\` enum('direct','string','number','integer','boolean','date','datetime','list','enum_map') NOT NULL DEFAULT 'direct',
  \`valueMap\` json DEFAULT NULL,
  \`confidence\` int NOT NULL DEFAULT '100',
  \`isActive\` tinyint(1) NOT NULL DEFAULT '1',
  \`notes\` text,
  \`updatedById\` int DEFAULT NULL,
  \`createdAt\` timestamp NOT NULL DEFAULT (now()),
  \`updatedAt\` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`),
  KEY \`mls_field_mappings_source_idx\` (\`sourceId\`,\`resource\`),
  KEY \`mls_field_mappings_field_idx\` (\`sourceField\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  },
  {
    table: "mls_metadata_snapshots",
    sql: `CREATE TABLE IF NOT EXISTS \`mls_metadata_snapshots\` (
  \`id\` int NOT NULL AUTO_INCREMENT,
  \`feedId\` int NOT NULL,
  \`resource\` varchar(32) NOT NULL,
  \`fieldCount\` int NOT NULL DEFAULT '0',
  \`localFieldCount\` int NOT NULL DEFAULT '0',
  \`fields\` json DEFAULT NULL,
  \`metadataHash\` varchar(64) DEFAULT NULL,
  \`fetchedAt\` datetime NOT NULL,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`mls_metadata_snapshots_feed_resource_uq\` (\`feedId\`,\`resource\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  },
  {
    table: "mls_provider_usage",
    sql: `CREATE TABLE IF NOT EXISTS \`mls_provider_usage\` (
  \`id\` bigint unsigned NOT NULL AUTO_INCREMENT,
  \`credentialRef\` varchar(64) NOT NULL,
  \`provider\` varchar(32) NOT NULL,
  \`windowStart\` datetime NOT NULL,
  \`requests\` int NOT NULL DEFAULT '0',
  \`bytes\` bigint NOT NULL DEFAULT '0',
  \`mediaRequests\` int NOT NULL DEFAULT '0',
  \`mediaBytes\` bigint NOT NULL DEFAULT '0',
  \`throttled\` int NOT NULL DEFAULT '0',
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`mls_provider_usage_window_uq\` (\`credentialRef\`,\`windowStart\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  },
  {
    table: "mls_worker_heartbeats",
    sql: `CREATE TABLE IF NOT EXISTS \`mls_worker_heartbeats\` (
  \`workerId\` varchar(160) NOT NULL,
  \`startedAt\` datetime NOT NULL,
  \`lastBeatAt\` datetime NOT NULL,
  \`version\` varchar(64) DEFAULT NULL,
  \`detail\` mediumtext,
  PRIMARY KEY (\`workerId\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  },
  {
    table: "mls_import_exceptions",
    sql: `CREATE TABLE IF NOT EXISTS \`mls_import_exceptions\` (
  \`id\` bigint unsigned NOT NULL AUTO_INCREMENT,
  \`feedId\` int NOT NULL,
  \`resource\` varchar(32) NOT NULL,
  \`providerKey\` varchar(160) NOT NULL,
  \`payloadGzip\` mediumblob NOT NULL,
  \`sourceModifiedAt\` datetime(3) DEFAULT NULL,
  \`errorCode\` varchar(64) NOT NULL,
  \`errorColumn\` varchar(64) DEFAULT NULL,
  \`attempts\` int NOT NULL DEFAULT '1',
  \`firstSeenAt\` datetime NOT NULL,
  \`lastSeenAt\` datetime NOT NULL,
  \`nextRetryAt\` datetime NOT NULL,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`mls_import_exceptions_feed_resource_key_uq\` (\`feedId\`,\`resource\`,\`providerKey\`),
  KEY \`mls_import_exceptions_retry_idx\` (\`feedId\`,\`nextRetryAt\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  },
];
