import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

const transactionsRouter = () => readFileSync("server/routers/transactions.ts", "utf-8");
const payoutPersistence = () => readFileSync("server/db.ts", "utf-8");

describe("transaction split recalculation memo preservation", () => {
  it("keeps auto-generated payout rows with saved eXp memo numbers while updating their split values", () => {
    const source = transactionsRouter();
    const recalculateSplits = source.slice(
      source.indexOf("recalculateSplits: protectedProcedure"),
      source.indexOf("updatePayoutOverride: protectedProcedure")
    );

    expect(recalculateSplits).toContain("isNull(transactionPayoutItems.expMemoNumber)");
    expect(recalculateSplits).toContain("eq(transactionPayoutItems.isAutoGenerated, true)");
    expect(recalculateSplits).toContain('ne(transactionPayoutItems.status, "settled")');
    expect(recalculateSplits).toContain("generateAutoPayouts({");
  });

  it("updates existing automatic payout rows without changing their saved eXp memo numbers", () => {
    const source = payoutPersistence();
    const upsert = source.slice(
      source.indexOf("export async function upsertAutoPayoutItem"),
      source.indexOf("export async function createPayoutItem")
    );

    expect(upsert).toContain("percentage: data.percentage");
    expect(upsert).toContain("amount: data.amount");
    expect(upsert).not.toContain("expMemoNumber:");
  });
});
