import { TRPCError } from "@trpc/server";
import { and, eq, inArray, isNull } from "drizzle-orm";
import { z } from "zod";
import { pulseMeetingUpdates, pulsePersonalInputs, pulseScorecardEntries, pulseScorecardMetrics } from "../../drizzle/schema";
import { getDb } from "../db";
import { protectedProcedure, router } from "../_core/trpc";
import { visible_meeting_ids } from "./access";
import { listAccessibleItems } from "./workItems";

const uuid=()=>crypto.randomUUID(); const week=()=>{const d=new Date();d.setDate(d.getDate()-((d.getDay()+6)%7));d.setHours(0,0,0,0);return d;};
async function dbOrThrow(){const db=await getDb();if(!db)throw new TRPCError({code:"INTERNAL_SERVER_ERROR",message:"Pulse is not available right now. Please try again."});return db;}
async function myMeetings(db:any,personId:number){const ids=await visible_meeting_ids(db,personId);return ids;}

export const pulsePersonalRouter=router({
  inputs: protectedProcedure.query(async({ctx})=>{const db=await dbOrThrow();const ids=await myMeetings(db,ctx.user.id);if(!ids.length)return {weekOf:week(),fields:[],complete:true};const metrics=await db.select({id:pulseScorecardMetrics.id,title:pulseScorecardMetrics.title,targetValue:pulseScorecardMetrics.targetValue,meetingId:pulseScorecardMetrics.meetingId,meetingName:(await import("../../drizzle/schema")).pulseMeetings.name,ownerId:pulseScorecardMetrics.ownerId}).from(pulseScorecardMetrics).leftJoin((await import("../../drizzle/schema")).pulseMeetings,eq((await import("../../drizzle/schema")).pulseMeetings.id,pulseScorecardMetrics.meetingId)).where(and(inArray(pulseScorecardMetrics.meetingId,ids),eq(pulseScorecardMetrics.ownerId,ctx.user.id),isNull(pulseScorecardMetrics.deletedAt)));
    const fields=[] as any[];for(const metric of metrics){const [entry]=await db.select().from(pulseScorecardEntries).where(and(eq(pulseScorecardEntries.metricId,metric.id),eq(pulseScorecardEntries.personId,ctx.user.id),eq(pulseScorecardEntries.periodStart,week()),isNull(pulseScorecardEntries.deletedAt)));fields.push({key:`metric:${metric.id}`,kind:"number",label:metric.title,target:metric.targetValue,meetingId:metric.meetingId,meetingName:metric.meetingName,value:entry?.value??null});}
    const [brief]=await db.select().from(pulsePersonalInputs).where(and(eq(pulsePersonalInputs.personId,ctx.user.id),eq(pulsePersonalInputs.inputKey,"brief"),eq(pulsePersonalInputs.weekOf,week()),isNull(pulsePersonalInputs.deletedAt)));fields.push({key:"brief",kind:"text",label:"60-second measurables brief",meetingName:"Your week",value:brief?.textValue??""});
    for(const type of ["segue","headline"] as const){const [update]=await db.select().from(pulseMeetingUpdates).where(and(inArray(pulseMeetingUpdates.meetingId,ids),eq(pulseMeetingUpdates.authorId,ctx.user.id),eq(pulseMeetingUpdates.updateType,type),isNull(pulseMeetingUpdates.deletedAt))).limit(1);fields.push({key:type,kind:"text",label:type==="segue"?"Segue":"Headlines",meetingName:update?"Saved to your meeting":"Choose a meeting when you save",value:update?.body??""});}
    const required=fields.filter(f=>f.kind==="number");return {weekOf:week(),fields,complete:required.every(f=>f.value!==null)};
  }),
  saveInput: protectedProcedure.input(z.object({key:z.string().min(1).max(100),value:z.union([z.number().int(),z.string().max(8000)]),meetingId:z.string().uuid().optional()})).mutation(async({ctx,input})=>{const db=await dbOrThrow();const ids=await myMeetings(db,ctx.user.id);if(input.key.startsWith("metric:")){const metricId=input.key.slice(7);const [metric]=await db.select().from(pulseScorecardMetrics).where(and(eq(pulseScorecardMetrics.id,metricId),eq(pulseScorecardMetrics.ownerId,ctx.user.id),inArray(pulseScorecardMetrics.meetingId,ids),isNull(pulseScorecardMetrics.deletedAt)));if(!metric)throw new TRPCError({code:"NOT_FOUND",message:"That input is not available."});await db.insert(pulseScorecardEntries).values({id:uuid(),metricId,personId:ctx.user.id,periodStart:week(),value:Number(input.value)}).onDuplicateKeyUpdate({set:{value:Number(input.value),deletedAt:null}});return{success:true};}
    if(input.key==="brief"){await db.insert(pulsePersonalInputs).values({id:uuid(),personId:ctx.user.id,meetingId:null,inputKey:"brief",weekOf:week(),textValue:String(input.value)}).onDuplicateKeyUpdate({set:{textValue:String(input.value),deletedAt:null}});return{success:true};}
    if(input.key==="segue"||input.key==="headline"){const meetingId=input.meetingId??ids[0];if(!meetingId||!ids.includes(meetingId))throw new TRPCError({code:"NOT_FOUND",message:"Choose a meeting you belong to."});await db.insert(pulseMeetingUpdates).values({id:uuid(),meetingId,authorId:ctx.user.id,updateType:input.key,body:String(input.value)});return{success:true};}throw new TRPCError({code:"BAD_REQUEST",message:"That input is not available."});
  }),
  dashboard: protectedProcedure.query(async({ctx})=>{const db=await dbOrThrow();const ids=await myMeetings(db,ctx.user.id);if(ids.length<=1)return {redirectMeetingId:ids[0]??null,items:[]};const all=await listAccessibleItems(db,ctx.user.id,{});const items=all.filter((item:any)=>item.assigneeId===ctx.user.id||item.ownerPersonId===ctx.user.id).map((item:any)=>({...item,source:item.meetingName??"Personal"}));const sort=(a:any,b:any)=>Number(b.isOverdue)-Number(a.isOverdue)||(a.dueDate??"9999").localeCompare(b.dueDate??"9999")||a.source.localeCompare(b.source);return {redirectMeetingId:null,items:{todos:items.filter((i:any)=>i.type==="todo").sort(sort),issues:items.filter((i:any)=>i.type==="issue"&&i.status!=="solved").sort(sort),rocks:items.filter((i:any)=>i.type==="rock").sort(sort)}};
  }),
});
