import fs from "node:fs/promises";
import mysql from "mysql2/promise";
import { SignJWT } from "jose";
import { getDb } from "../server/db";
import { generatePulseObservations } from "../server/pulse/observations";
import { resetPulseThinSliceFixture, retirePulseThinSliceFixture } from "../server/pulse/thinSlice";

const url = process.env.DATABASE_URL; const secret = process.env.JWT_SECRET; const appId = process.env.VITE_APP_ID; const base = process.env.PULSE_VERIFICATION_URL ?? "http://localhost:3003";
if (!url || !secret || !appId) throw new Error("DATABASE_URL, JWT_SECRET, and VITE_APP_ID are required");
const sql = await mysql.createConnection({ uri: url }); const db = await getDb(); if (!db) throw new Error("Database unavailable"); const prefix = "Pulse Prompt 8 Fixture"; let passed = false;
async function token(person: any) { return new SignJWT({ openId: person.openId, appId, name: person.name }).setProtectedHeader({ alg: "HS256", typ: "JWT" }).setIssuedAt().setExpirationTime("15m").sign(new TextEncoder().encode(secret)); }
async function call(person: any, procedure: string, input?: unknown, type: "query" | "mutation" = "query") { const endpoint = new URL(`${base}/api/trpc/${procedure}`); const headers: Record<string, string> = { cookie: `app_session_id=${await token(person)}` }; const options: RequestInit = { headers }; if (type === "query") endpoint.searchParams.set("input", JSON.stringify({ json: input ?? null })); else { options.method = "POST"; headers["content-type"] = "application/json"; options.body = JSON.stringify({ json: input ?? null }); } const response = await fetch(endpoint, options); const raw = await response.json(); return { status: response.status, value: raw?.result?.data?.json, message: raw?.error?.json?.message ?? "" }; }

try {
  await resetPulseThinSliceFixture(db);
  const [people] = await sql.query<any[]>("SELECT id, openId, name FROM users WHERE openId LIKE 'pulse_slice_fixture_%'"); const person = Object.fromEntries(people.map((row) => [row.openId.slice(-2).toUpperCase(), row]));
  const [meetings] = await sql.query<any[]>("SELECT id, name FROM pulse_meetings WHERE name LIKE 'Pulse Slice — %' AND deletedAt IS NULL"); const meeting = Object.fromEntries(meetings.map((row) => [row.name.slice(-1), row]));
  const [members] = await sql.query<any[]>("SELECT meetingId, personId, meetingRole FROM pulse_meeting_members WHERE meetingId IN (?, ?, ?) AND removedAt IS NULL AND deletedAt IS NULL", [meeting.A.id, meeting.B.id, meeting.C.id]);
  const ownerId = members.find((member) => member.meetingId === meeting.A.id && member.meetingRole === "owner")?.personId; const owner = people.find((row) => row.id === ownerId); const member = people.find((row) => row.id !== ownerId && members.some((membership) => membership.meetingId === meeting.A.id && membership.personId === row.id)); const rockViewerId = members.find((membership) => membership.meetingId === meeting.B.id)?.personId; const rockViewer = people.find((row) => row.id === rockViewerId);
  if (!owner || !member || !rockViewer) throw new Error("Prompt 8 fixture needs an owner and ordinary member in meeting A plus a member in meeting B.");
  await sql.query("UPDATE pulse_meetings SET sectionsEnabled = JSON_SET(JSON_SET(sectionsEnabled, '$.goals', true), '$.rocks', true), sectionOrder = JSON_ARRAY_APPEND(sectionOrder, '$', 'goals') WHERE id = ? AND NOT JSON_CONTAINS(sectionOrder, JSON_QUOTE('goals'))", [meeting.A.id]);
  await sql.query("UPDATE pulse_meetings SET sectionsEnabled = JSON_SET(sectionsEnabled, '$.rocks', true), sectionOrder = JSON_ARRAY_APPEND(sectionOrder, '$', 'rocks') WHERE id = ? AND NOT JSON_CONTAINS(sectionOrder, JSON_QUOTE('rocks'))", [meeting.B.id]);
  const [goalResult] = await sql.query<any>("INSERT INTO company_goals (title, description, ownerId, year, targetValue, currentValue, unit, status, createdById) VALUES (?, ?, ?, YEAR(CURDATE()), 100, 40, 'number', 'active', ?)", [prefix, "A company-level Prompt 8 fixture goal.", owner.id, owner.id]); const goalId = Number(goalResult.insertId);
  await sql.query("INSERT INTO meeting_goals (id, meetingId, savvyosGoalId, sortOrder) VALUES (UUID(), ?, ?, 0)", [meeting.A.id, goalId]);
  const [responsibility] = await sql.query<any>("INSERT INTO roles_responsibilities (ownerId, title, description, cadence, status, createdById) VALUES (?, ?, ?, 'weekly', 'active', ?)", [owner.id, `${prefix} responsibility`, "Fixture responsibility", owner.id]);
  const [metricResult] = await sql.query<any>("INSERT INTO rr_scorecard_metrics (responsibilityId, name, metricType, frequency, targetValue, performanceDirection, displayFormat, rollupMethod, status, createdById) VALUES (?, ?, 'manual', 'weekly', 10, 'higher', 'number', 'sum', 'active', ?)", [Number(responsibility.insertId), `${prefix} metric`, owner.id]); const metricId = Number(metricResult.insertId);
  await sql.query("INSERT INTO meeting_scorecard_metrics (id, meetingId, savvyosMetricId, sortOrder, addedById) VALUES (UUID(), ?, ?, 0, ?)", [meeting.A.id, metricId, owner.id]);
  const starts = ["2026-08-17", "2026-08-10", "2026-08-03"]; for (const [index, start] of starts.entries()) { const end = ["2026-08-23", "2026-08-16", "2026-08-09"][index]; await sql.query("INSERT INTO rr_metric_values (metricId, periodStart, periodEnd, actualValue, valueSource, enteredById, enteredAt) VALUES (?, ?, ?, ?, 'manual', ?, NOW())", [metricId, start, end, String(3 + index), owner.id]); }
  const rockId = crypto.randomUUID();
  await sql.query("INSERT INTO pulse_work_items (id, type, title, meetingId, ownerPersonId, assigneeId, createdById, status, quarter, percentComplete, percentSource) VALUES (?, 'rock', ?, ?, NULL, ?, ?, 'on_track', 'Q3 2026', 35, 'manual')", [rockId, `${prefix} rock`, meeting.A.id, owner.id, owner.id]);
  await sql.query("INSERT INTO meeting_rocks (id, meetingId, workItemId, sortOrder) VALUES (UUID(), ?, ?, 0)", [meeting.B.id, rockId]);
  const memberDashboard = await call(member, "pulse.meetingViews.dashboard", { meetingId: meeting.A.id }); const memberGoals = memberDashboard.value?.sections?.find((section: any) => section.section === "goals");
  const ownerDashboard = await call(owner, "pulse.meetingViews.dashboard", { meetingId: meeting.A.id }); const scorecard = ownerDashboard.value?.sections?.find((section: any) => section.section === "scorecard");
  const mappedRock = await call(rockViewer, "pulse.meetingViews.dashboard", { meetingId: meeting.B.id }); const rocks = mappedRock.value?.sections?.find((section: any) => section.section === "rocks");
  const workBefore = await sql.query<any[]>("SELECT id FROM pulse_work_items WHERE title LIKE ?", [`${prefix}%`]); const notificationBefore = await sql.query<any[]>("SELECT id FROM pulse_notifications WHERE body LIKE ?", [`%${prefix}%`]); const generation = await generatePulseObservations(); const observations = await call(owner, "pulse.observations.forMeeting", { meetingId: meeting.A.id }); const workAfterGeneration = await sql.query<any[]>("SELECT id FROM pulse_work_items WHERE title LIKE ?", [`${prefix}%`]); const notificationAfterGeneration = await sql.query<any[]>("SELECT id FROM pulse_notifications WHERE body LIKE ?", [`%${prefix}%`]);
  const observation = observations.value?.find((row: any) => row.metricId === metricId); const proposed = observation ? await call(member, "pulse.observations.raiseAsIssue", { observationId: observation.id, meetingId: meeting.A.id }, "mutation") : { status: 500, value: null };
  const [proposalRows] = await sql.query<any[]>("SELECT isProposed, origin, savvyosMetricId, assigneeId FROM pulse_work_items WHERE id = ?", [proposed.value?.workItemId ?? "none"]);
  const [proposalNotifications] = await sql.query<any[]>("SELECT personId, requiresAction FROM pulse_notifications WHERE sourceId = ? AND notificationType = 'proposed_issue'", [proposed.value?.workItemId ?? "none"]);
  const accepted = proposed.value?.workItemId ? await call(member, "pulse.observations.acceptProposal", { workItemId: proposed.value.workItemId }, "mutation") : { status: 500 }; const [acceptedRow] = await sql.query<any[]>("SELECT isProposed FROM pulse_work_items WHERE id = ?", [proposed.value?.workItemId ?? "none"]);
  const forbiddenGlobalRocks = await call(member, "pulse.rocks.globalQuarterly");
  const schema = await fs.readFile("/home/ubuntu/savvyos/drizzle/schema.ts", "utf8"); const scorecardComponent = await fs.readFile("/home/ubuntu/savvyos/client/src/components/pulse/PulseScorecard.tsx", "utf8"); const attentionComponent = await fs.readFile("/home/ubuntu/savvyos/client/src/components/pulse/PulseNeedsAttention.tsx", "utf8");
  const report = { generatedAt: new Date().toISOString(), acceptance: {
    annualGoalsVisibleToMembers: { pass: memberDashboard.status === 200 && memberGoals?.items?.some((goal: any) => goal.goalId === goalId && goal.percentComplete === 40) },
    goalsIndependentOfRocks: { pass: memberDashboard.value?.meeting?.sectionsEnabled?.goals === true && schema.includes('mysqlTable("meeting_goals"') && !schema.includes('mysqlTable("pulse_goal') },
    rockMappingReadOnlyElsewhere: { pass: rocks?.items?.some((rock: any) => rock.id === rockId && rock.readOnly === true && rock.homeMeetingName.includes("Pulse Slice — A")) },
    globalRocksForbiddenForMember: { pass: forbiddenGlobalRocks.status === 403 && /super admins only/.test(forbiddenGlobalRocks.message) },
    trendInlineNoChart: { pass: scorecard?.items?.some((metric: any) => metric.metricId === metricId && /3rd week declining/.test(metric.trend ?? "")) && scorecardComponent.includes("Trend") && !scorecardComponent.includes("chart") },
    needsAttentionBoundedAndManagerOnly: { pass: (ownerDashboard.value?.attention ?? []).length <= 5 && (ownerDashboard.value?.attention ?? []).some((item: any) => item.metricId === metricId) && memberDashboard.value?.attention === undefined && attentionComponent.includes("items.slice(0, 5)") },
    generationWritesObservationsOnly: { pass: generation.written >= 1 && observations.value?.some((row: any) => row.metricId === metricId) && workAfterGeneration[0].length === workBefore[0].length && notificationAfterGeneration[0].length === notificationBefore[0].length },
    humanRaisedProposalOnly: { pass: proposed.status === 200 && proposalRows[0]?.isProposed === 1 && proposalRows[0]?.origin === "ai_proposed" && proposalRows[0]?.savvyosMetricId === metricId && proposalRows[0]?.assigneeId == null && proposalNotifications.every((row: any) => row.requiresAction === 1) && accepted.status === 200 && acceptedRow[0]?.isProposed === 0 },
    accessibleTrendSignals: { pass: scorecardComponent.includes("ArrowDown") && scorecardComponent.includes("metric.trend") && scorecardComponent.includes("Off target") },
  }};
  await fs.writeFile("/home/ubuntu/savvyos/docs/pulse_prompt_8_verification.json", `${JSON.stringify(report, null, 2)}\n`); if (!Object.values(report.acceptance).every((value: any) => value.pass === true)) throw new Error("Prompt 8 acceptance failed; inspect docs/pulse_prompt_8_verification.json"); passed = true; console.log("Prompt 8 acceptance passed");
} finally {
  await sql.query("DELETE mapping FROM meeting_goals mapping JOIN company_goals goal ON goal.id = mapping.savvyosGoalId WHERE goal.title = ?", [prefix]); await sql.query("DELETE FROM company_goals WHERE title = ?", [prefix]); await sql.query("DELETE mapping FROM meeting_rocks mapping JOIN pulse_work_items item ON item.id = mapping.workItemId WHERE item.title LIKE ?", [`${prefix}%`]); await sql.query("DELETE FROM pulse_work_items WHERE title LIKE ?", [`${prefix}%`]); await sql.query("DELETE FROM roles_responsibilities WHERE title = ?", [`${prefix} responsibility`]); await retirePulseThinSliceFixture(db); await sql.end();
}
if (passed) process.exit(0);
