import fs from "node:fs/promises";
import mysql from "mysql2/promise";
import { SignJWT } from "jose";
import { getDb } from "../server/db";
import { resetPulseThinSliceFixture, retirePulseThinSliceFixture } from "../server/pulse/thinSlice";
import { pulseCascadingMessages, pulseScorecardMetrics } from "../drizzle/schema";

const databaseUrl = process.env.DATABASE_URL; const jwtSecret = process.env.JWT_SECRET; const appId = process.env.VITE_APP_ID; const baseUrl = process.env.PULSE_VERIFICATION_URL ?? "http://localhost:3003";
if (!databaseUrl || !jwtSecret || !appId) throw new Error("DATABASE_URL, JWT_SECRET, and VITE_APP_ID are required.");
const db = await mysql.createConnection({ uri: databaseUrl }); const reportPath = "/home/ubuntu/savvyos/docs/pulse_prompt_3_verification.json";
const id = () => crypto.randomUUID(); const stable = (v: unknown) => JSON.stringify(v);
async function tokenFor(person:any) { return new SignJWT({ openId: person.openId, appId, name: person.name }).setProtectedHeader({ alg:"HS256",typ:"JWT" }).setIssuedAt().setExpirationTime("15m").sign(new TextEncoder().encode(jwtSecret)); }
async function call(person:any, procedure:string, input?:unknown, type:"query"|"mutation"="query") { const token=await tokenFor(person); const url=new URL(`${baseUrl}/api/trpc/${procedure}`); const options:any={headers:{cookie:`app_session_id=${token}`}}; if(type==="query")url.searchParams.set("input",JSON.stringify({json:input??null}));else{options.method="POST";options.headers={...options.headers,"content-type":"application/json"};options.body=JSON.stringify({json:input??null});}const response=await fetch(url,options);const body=await response.json();return {status:response.status,value:body?.result?.data?.json,error:body?.error?.json??body?.error,raw:body}; }
try {
 const drizzle=await getDb(); if(!drizzle)throw new Error("Database unavailable"); await resetPulseThinSliceFixture(drizzle);
 const [people]=await db.query<any[]>("SELECT id, openId, name FROM users WHERE openId LIKE 'pulse_slice_fixture_%' ORDER BY openId"); const byKey=Object.fromEntries(people.map(p=>[p.openId.slice(-2).toUpperCase(),p])); const p1=byKey.P1,p2=byKey.P2,p4=byKey.P4;
 const [meetings]=await db.query<any[]>("SELECT id,name FROM pulse_meetings WHERE name LIKE 'Pulse Slice — %' AND deletedAt IS NULL"); const a=meetings.find(m=>m.name==="Pulse Slice — A"),c=meetings.find(m=>m.name==="Pulse Slice — C"); if(!p1||!p2||!p4||!a||!c)throw new Error("Missing marked verification fixture");
 const metricId=id(); const cascadeId=id(); await drizzle.insert(pulseScorecardMetrics).values({id:metricId,meetingId:a.id,title:"Initial Agent Meetings",targetValue:5,ownerId:p1.id,sortOrder:0}); await drizzle.insert(pulseCascadingMessages).values({id:cascadeId,fromMeetingId:c.id,toMeetingId:a.id,body:"Bring the platform decision to Leadership.",createdById:p2.id});
 const memberDash=await call(p1,"pulse.meetingViews.dashboard",{meetingId:a.id}); const memberRun=await call(p1,"pulse.meetingViews.run",{meetingId:a.id}); const managerDash=await call(p2,"pulse.meetingViews.dashboard",{meetingId:a.id}); const managerRun=await call(p2,"pulse.meetingViews.run",{meetingId:a.id}); const missing=await call(p4,"pulse.meetingViews.dashboard",{meetingId:"00000000-0000-0000-0000-000000000000"}); const denied=await call(p4,"pulse.meetingViews.dashboard",{meetingId:a.id});
 const beforeHeadline=stable(managerDash.value?.sections?.find((s:any)=>s.section==="headlines")); await call(p2,"pulse.meetingViews.addUpdate",{meetingId:a.id,updateType:"headline",body:"Controlled shared query update"},"mutation"); const dashAfter=await call(p2,"pulse.meetingViews.dashboard",{meetingId:a.id}); const runAfter=await call(p2,"pulse.meetingViews.run",{meetingId:a.id}); const afterHeadline=stable(dashAfter.value?.sections?.find((s:any)=>s.section==="headlines"));
 const score=await call(p1,"pulse.meetingViews.setScorecardValue",{metricId,value:4},"mutation"); const ack=await call(p1,"pulse.meetingViews.acknowledgeCascade",{messageId:cascadeId},"mutation"); const conclude=await call(p2,"pulse.meetingViews.conclude",{meetingId:a.id,rating:8,durationActualMinutes:44,attendeeIds:[p1.id,p2.id],notes:"Prompt 3 fixture conclusion"},"mutation");
 const [archive]=await db.query<any[]>("SELECT attendeeIds, durationActualMinutes, todosCreated, todosCompleted, issuesCreated, issuesResolved, rating, notes FROM pulse_meetings_archive WHERE meetingId=? ORDER BY occurredAt DESC LIMIT 1",[a.id]); const fileChecks=await Promise.all(["segue","headlines","scorecard","goals","rocks","todos","issues","cascading","conclude"].map(async section=>({section,hasExport:(await fs.readFile(`/home/ubuntu/savvyos/server/pulse/sections/${section}.ts`,"utf8")).includes("export async function getSectionData")})));
 const dashboardSections=dashAfter.value?.sections??[];const runnerSections=runAfter.value?.sections??[];const prohibited=["run","configuration","archive","effectiveness"]; const memberKeys=Object.keys(memberDash.value??{}); const report={generatedAt:new Date().toISOString(),fixture:{meetingA:a.id,meetingC:c.id},acceptance:{nineModules:{pass:fileChecks.every(x=>x.hasExport),evidence:fileChecks},dashboardRunnerDeepEquality:{pass:stable(dashboardSections)===stable(runnerSections),dashboard:dashboardSections,runner:runnerSections},controlledSectionUpdate:{pass:beforeHeadline!==afterHeadline&&stable(dashAfter.value?.sections?.find((s:any)=>s.section==="headlines"))===stable(runAfter.value?.sections?.find((s:any)=>s.section==="headlines")),before:beforeHeadline,after:afterHeadline},memberSafeMarkup:{pass:memberDash.status===200&&!memberDash.value?.manager&&prohibited.every(k=>!memberKeys.includes(k)),keys:memberKeys},runRoleGate:{pass:memberRun.status===404&&managerRun.status===200&&!!managerRun.value?.run,memberStatus:memberRun.status,managerStatus:managerRun.status},missingAndDeniedIdentical:{pass:missing.status===denied.status&&stable(missing.raw)===stable(denied.raw),missingStatus:missing.status,deniedStatus:denied.status},inlineActions:{pass:score.status===200&&ack.status===200,scoreStatus:score.status,ackStatus:ack.status},cascadingRouting:{pass:(dashboardSections.find((s:any)=>s.section==="cascading")?.items??[]).some((i:any)=>i.fromMeetingName==="Pulse Slice — C"&&i.toMeetingName==="Pulse Slice — A"),payload:dashboardSections.find((s:any)=>s.section==="cascading")},conclusionArchive:{pass:conclude.status===200&&archive[0]?.rating===8&&archive[0]?.durationActualMinutes===44&&archive[0]?.notes==="Prompt 3 fixture conclusion",record:archive[0]}}};
 const tests=Object.values(report.acceptance).map((v:any)=>v.pass); await db.query("UPDATE pulse_scorecard_metrics SET deletedAt=NOW() WHERE meetingId IN (?,?)",[a.id,c.id]); await db.query("UPDATE pulse_cascading_messages SET deletedAt=NOW() WHERE fromMeetingId IN (?,?) OR toMeetingId IN (?,?)",[a.id,c.id,a.id,c.id]); await db.query("UPDATE pulse_meeting_updates SET deletedAt=NOW() WHERE meetingId IN (?,?)",[a.id,c.id]); const retirement=await retirePulseThinSliceFixture(drizzle); (report as any).fixtureRetirement={pass:retirement.people===7&&retirement.meetings===3,retirement}; await fs.writeFile(reportPath,JSON.stringify(report,null,2)+"\n"); if(!tests.every(Boolean)||(report as any).fixtureRetirement.pass!==true)throw new Error(`Prompt 3 verification failed: ${JSON.stringify(report.acceptance)}`); console.log(`Prompt 3 acceptance passed: ${reportPath}`);
} finally { await db.end(); }
