/**
 * Common RESO Data Dictionary 2.x Property field names. Used only as a
 * fallback to tell a standard field from an MLS local field when the adapter
 * and the metadata snapshot cannot say. Unmapped standard fields stay in the
 * raw payload; unmapped local fields are kept in mls_listings.localFields.
 */
const NAMES = `
AboveGradeFinishedArea AboveGradeFinishedAreaSource AboveGradeFinishedAreaUnits AccessCode AccessibilityFeatures
AdditionalParcelsDescription AdditionalParcelsYN AnchorsCoTenants Appliances ArchitecturalStyle AssociationAmenities
AssociationFee AssociationFee2 AssociationFee2Frequency AssociationFeeFrequency AssociationFeeIncludes AssociationName
AssociationName2 AssociationPhone AssociationPhone2 AssociationYN AttachedGarageYN AvailabilityDate Basement BasementYN
BathroomsFull BathroomsHalf BathroomsOneQuarter BathroomsPartial BathroomsThreeQuarter BathroomsTotalInteger
BathroomsTotalDecimal BedroomsPossible BedroomsTotal BelowGradeFinishedArea BelowGradeFinishedAreaSource
BelowGradeFinishedAreaUnits BodyType BuilderModel BuilderName BuildingAreaSource BuildingAreaTotal BuildingAreaUnits
BuildingFeatures BuildingName BusinessName BusinessType BuyerAgencyCompensation BuyerAgencyCompensationType BuyerAgentAOR
BuyerAgentDesignation BuyerAgentDirectPhone BuyerAgentEmail BuyerAgentFirstName BuyerAgentFullName BuyerAgentKey
BuyerAgentKeyNumeric BuyerAgentLastName BuyerAgentMlsId BuyerAgentOfficePhone BuyerAgentPreferredPhone
BuyerAgentStateLicense BuyerFinancing BuyerOfficeAOR BuyerOfficeEmail BuyerOfficeKey BuyerOfficeKeyNumeric
BuyerOfficeMlsId BuyerOfficeName BuyerOfficePhone BuyerTeamKey BuyerTeamName CableTvExpense CancellationDate CapRate
CarportSpaces CarportYN CarrierRoute City CityRegion CloseDate ClosePrice CoBuyerAgentFullName CoBuyerAgentKey
CoBuyerAgentMlsId CoBuyerOfficeKey CoBuyerOfficeMlsId CoBuyerOfficeName CoListAgentDirectPhone CoListAgentEmail
CoListAgentFirstName CoListAgentFullName CoListAgentKey CoListAgentKeyNumeric CoListAgentLastName CoListAgentMlsId
CoListAgentStateLicense CoListOfficeKey CoListOfficeKeyNumeric CoListOfficeMlsId CoListOfficeName CoListOfficePhone
CommonInterest CommonWalls CommunityFeatures Concessions ConcessionsAmount ConcessionsComments ConstructionMaterials
ContinentRegion Contingency ContingentDate ContractStatusChangeDate Cooling CoolingYN CopyrightNotice Country
CountryRegion CountyOrParish CoveredSpaces CropsIncludedYN CrossStreet CultivatedArea CumulativeDaysOnMarket
CurrentFinancing CurrentUse DOH1 DOH2 DOH3 DaysOnMarket DevelopmentStatus DirectionFaces Directions Disclaimer
Disclosures DistanceToBusComments DistanceToElectricComments DistanceToSchoolsComments DistanceToSewerComments
DistanceToWaterComments DocumentsAvailable DocumentsChangeTimestamp DocumentsCount DoorFeatures DualVariableCompensationYN
Electric ElectricExpense ElectricOnPropertyYN ElementarySchool ElementarySchoolDistrict Elevation ElevationUnits
EntryLevel EntryLocation Exclusions ExistingLeaseType ExpirationDate ExteriorFeatures FarmCreditServiceInclYN
FarmLandAreaSource FarmLandAreaUnits Fencing FinancialDataSource FireplaceFeatures FireplaceYN FireplacesTotal Flooring
FoundationArea FoundationDetails FrontageLength FrontageType FuelExpense Furnished FurnitureReplacementExpense
GarageSpaces GarageYN GardenerExpense GrazingPermitsBlmYN GrazingPermitsForestServiceYN GrazingPermitsPrivateYN
GreenBuildingVerificationType GreenEnergyEfficient GreenEnergyGeneration GreenIndoorAirQuality GreenLocation
GreenSustainability GreenWaterConservation GrossIncome GrossScheduledIncome HabitableResidenceYN Heating HeatingYN
HighSchool HighSchoolDistrict HomeWarrantyYN HorseAmenities HorseYN HoursDaysOfOperation HoursDaysOfOperationDescription
IDXParticipationYN Inclusions IncomeIncludes InsuranceExpense InteriorFeatures InternetAddressDisplayYN
InternetAutomatedValuationDisplayYN InternetConsumerCommentYN InternetEntireListingDisplayYN IrrigationSource
IrrigationWaterRightsAcres IrrigationWaterRightsYN LaborInformation LandLeaseAmount LandLeaseAmountFrequency
LandLeaseExpirationDate LandLeaseYN Latitude LaundryFeatures LeasableArea LeasableAreaUnits LeaseAmount
LeaseAmountFrequency LeaseAssignableYN LeaseConsideredYN LeaseExpiration LeaseRenewalCompensation LeaseRenewalOptionYN
LeaseTerm Levels License1 License2 License3 LicensesExpense ListAOR ListAgentAOR ListAgentCellPhone ListAgentDesignation
ListAgentDirectPhone ListAgentEmail ListAgentFax ListAgentFirstName ListAgentFullName ListAgentHomePhone ListAgentKey
ListAgentKeyNumeric ListAgentLastName ListAgentMiddleName ListAgentMlsId ListAgentMobilePhone ListAgentNamePrefix
ListAgentNameSuffix ListAgentOfficePhone ListAgentOfficePhoneExt ListAgentPager ListAgentPreferredPhone
ListAgentPreferredPhoneExt ListAgentStateLicense ListAgentTollFreePhone ListAgentURL ListAgentVoiceMail
ListAgentVoiceMailExt ListOfficeAOR ListOfficeEmail ListOfficeFax ListOfficeKey ListOfficeKeyNumeric ListOfficeMlsId
ListOfficeName ListOfficePhone ListOfficePhoneExt ListOfficeURL ListPrice ListPriceLow ListTeamKey ListTeamName
ListingAgreement ListingContractDate ListingId ListingKey ListingKeyNumeric ListingService ListingTerms
LivingArea LivingAreaSource LivingAreaUnits LockBoxLocation LockBoxSerialNumber LockBoxType Longitude LotDimensionsSource
LotFeatures LotSizeAcres LotSizeArea LotSizeDimensions LotSizeSource LotSizeSquareFeet LotSizeUnits MLSAreaMajor
MLSAreaMinor MainLevelBathrooms MainLevelBedrooms MaintenanceExpense MajorChangeTimestamp MajorChangeType Make
MapCoordinate MapCoordinateSource MapURL MiddleOrJuniorSchool MiddleOrJuniorSchoolDistrict MlsStatus MobileDimUnits
MobileHomeRemainsYN MobileLength MobileWidth Model ModificationTimestamp NetOperatingIncome NewConstructionYN
NewTaxesExpense NumberOfBuildings NumberOfFullTimeEmployees NumberOfLots NumberOfPads NumberOfPartTimeEmployees
NumberOfSeparateElectricMeters NumberOfSeparateGasMeters NumberOfSeparateWaterMeters NumberOfUnitsInCommunity
NumberOfUnitsLeased NumberOfUnitsMoMo NumberOfUnitsTotal NumberOfUnitsVacant OccupantName OccupantPhone OccupantType
OffMarketDate OffMarketTimestamp OnMarketDate OnMarketTimestamp OpenParkingSpaces OpenParkingYN OperatingExpense
OperatingExpenseIncludes OriginalEntryTimestamp OriginalListPrice OriginatingSystemID OriginatingSystemKey
OriginatingSystemName OtherEquipment OtherExpense OtherParking OtherStructures OwnerName OwnerPays OwnerPhone Ownership
OwnershipType ParcelNumber ParkManagerName ParkManagerPhone ParkName ParkingFeatures ParkingTotal PastureArea
PatioAndPorchFeatures PendingTimestamp PestControlExpense PetsAllowed PhotosChangeTimestamp PhotosCount PoolExpense
PoolFeatures PoolPrivateYN Possession PossibleUse PostalCity PostalCode PostalCodePlus4 PowerProductionType
PreviousListPrice PriceChangeTimestamp PrivateOfficeRemarks PrivateRemarks ProfessionalManagementExpense PropertyAttachedYN
PropertyCondition PropertySubType PropertyType PublicRemarks PublicSurveyRange PublicSurveySection PublicSurveyTownship
PurchaseContractDate RVParkingDimensions RangeArea RentControlYN RentIncludes RoadFrontageType RoadResponsibility
RoadSurfaceType Roof RoomType RoomsTotal SeatingCapacity SecurityFeatures SeniorCommunityYN SerialU SerialX
SerialXX Sewer ShowingAdvanceNotice ShowingAttendedYN ShowingContactName ShowingContactPhone ShowingContactPhoneExt
ShowingContactType ShowingDays ShowingEndTime ShowingInstructions ShowingRequirements ShowingStartTime SignOnPropertyYN
Skirt SourceSystemID SourceSystemKey SourceSystemName SpaFeatures SpaYN SpecialLicenses SpecialListingConditions
StandardStatus StartShowingDate StateOrProvince StateRegion StatusChangeTimestamp Stories StoriesTotal StreetAdditionalInfo
StreetDirPrefix StreetDirSuffix StreetName StreetNumber StreetNumberNumeric StreetSuffix StreetSuffixModifier
StructureType SubAgencyCompensation SubAgencyCompensationType SubdivisionName SuppliesExpense SyndicateTo
SyndicationRemarks TaxAnnualAmount TaxAssessedValue TaxBlock TaxBookNumber TaxLegalDescription TaxLot TaxMapNumber
TaxOtherAnnualAssessmentAmount TaxParcelLetter TaxStatusCurrent TaxTract TaxYear TenantPays Topography TotalActualRent
Township TransactionBrokerCompensation TransactionBrokerCompensationType TrashExpense UnitNumber UnitTypeType
UnitsFurnished UniversalPropertyId UniversalPropertySubId UnparsedAddress Utilities VacancyAllowance VacancyAllowanceRate
Vegetation VideosChangeTimestamp VideosCount View ViewYN VirtualTourURLBranded VirtualTourURLUnbranded WalkScore
WaterBodyName WaterSewerExpense WaterSource WaterfrontFeatures WaterfrontYN WindowFeatures WithdrawnDate WoodedArea
WorkmansCompensationExpense YearBuilt YearBuiltDetails YearBuiltEffective YearBuiltSource YearEstablished YearsCurrentOwner
Zoning ZoningDescription
`;

export const RESO_STANDARD_PROPERTY_FIELDS: ReadonlySet<string> = new Set(NAMES.split(/\s+/).filter(Boolean));

export function isKnownResoField(name: string): boolean {
  return RESO_STANDARD_PROPERTY_FIELDS.has(name);
}
