import { useMemo, useState } from "react";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, BarChart3, ChevronRight, CircleDotDashed, Flag, Loader2, Plus, Save, Target, UsersRound } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { toast } from "sonner";

const NODE_LABELS: Record<string, string> = { vision: "Vision", annual_goal: "Annual goal", quarterly_rock: "Quarterly Rock", milestone: "Milestone" };
const STATUS_LABELS: Record<string, string> = { not_started: "Not started", on_track: "On track", at_risk: "At risk", complete: "Complete", skipped: "Skipped" };

export function PulseScorecardsStrategyPanel() {
  const utils = trpc.useUtils();
  const { data: scopes = [] } = trpc.pulse.visibleScopes.useQuery(undefined, { staleTime: 10000 });
  const { data: foundation } = trpc.pulse.getFoundation.useQuery(undefined, { staleTime: 20000 });
  const [scopeId, setScopeId] = useState("");
  const currentScopeId = Number(scopeId || scopes[0]?.id || 0);
  const { data: scorecard, isLoading: scorecardLoading } = trpc.pulse.scorecard.useQuery({ scopeId: currentScopeId || 1 }, { enabled: !!currentScopeId, staleTime: 5000 });
  const { data: strategy } = trpc.pulse.strategy.useQuery({ scopeId: currentScopeId || 1 }, { enabled: !!currentScopeId, staleTime: 5000 });
  const [measurableOpen, setMeasurableOpen] = useState(false);
  const [strategyOpen, setStrategyOpen] = useState(false);
  const [entryDrafts, setEntryDrafts] = useState<Record<number, string>>({});
  const [measurable, setMeasurable] = useState({ name: "", unit: "count", cadence: "weekly" as "weekly" | "monthly" | "quarterly", direction: "higher_is_better" as "higher_is_better" | "lower_is_better", targetValue: "", warningValue: "", criticalValue: "", ownerPersonId: "" });
  const [node, setNode] = useState({ nodeType: "vision" as "vision" | "annual_goal" | "quarterly_rock" | "milestone", parentId: "", title: "", accountablePersonId: "", responsiblePersonId: "", dueOn: "" });
  const people = foundation?.people?.filter((person: any) => person.isActive) ?? [];
  const activeScope = scopes.find((scope: any) => scope.id === currentScopeId);
  const invalidate = () => { utils.pulse.scorecard.invalidate(); utils.pulse.strategy.invalidate(); utils.pulse.vto.invalidate(); utils.pulse.getFoundation.invalidate(); };
  const createMeasurable = trpc.pulse.createMeasurable.useMutation({ onSuccess: () => { toast.success("Measurable created with Scope placement"); setMeasurableOpen(false); setMeasurable({ name: "", unit: "count", cadence: "weekly", direction: "higher_is_better", targetValue: "", warningValue: "", criticalValue: "", ownerPersonId: "" }); invalidate(); }, onError: (error) => toast.error(error.message) });
  const recordEntry = trpc.pulse.recordMeasurableEntry.useMutation({ onSuccess: (result) => { toast.success(result.alertState ? `${result.alertState} alert evaluated` : "Scorecard entry saved"); invalidate(); }, onError: (error) => toast.error(error.message) });
  const createNode = trpc.pulse.createStrategyNode.useMutation({ onSuccess: () => { toast.success("Strategy node created in the shared hierarchy"); setStrategyOpen(false); setNode({ nodeType: "vision", parentId: "", title: "", accountablePersonId: "", responsiblePersonId: "", dueOn: "" }); invalidate(); }, onError: (error) => toast.error(error.message) });
  const setStatus = trpc.pulse.setStrategyStatus.useMutation({ onSuccess: invalidate, onError: (error) => toast.error(error.message) });
  const nodes = strategy?.nodes ?? [];
  const potentialParents = nodes.filter((candidate: any) => ({ annual_goal: candidate.nodeType === "vision", quarterly_rock: candidate.nodeType === "annual_goal", milestone: candidate.nodeType === "quarterly_rock" } as any)[node.nodeType]);
  const alertCount = scorecard?.rows.filter((row: any) => row.alert).length ?? 0;

  return <div className="space-y-4">
    <Card className="border-primary/20 bg-gradient-to-br from-primary/[0.05] to-transparent"><CardHeader className="flex flex-row flex-wrap items-start justify-between gap-4"><div><CardTitle>Scorecards and strategy</CardTitle><CardDescription className="mt-1 max-w-3xl">Measurables are placed in Scopes, values are one cell per calendar period, and Vision → Annual goal → Quarterly Rock → Milestone is the single planning hierarchy. VTO is a view, never a duplicate tree.</CardDescription></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => setStrategyOpen(true)} disabled={!currentScopeId}><Plus className="mr-1.5 h-3.5 w-3.5" />Strategy node</Button><Button onClick={() => setMeasurableOpen(true)} disabled={!currentScopeId}><Plus className="mr-1.5 h-3.5 w-3.5" />Measurable</Button></div></CardHeader><CardContent><Select value={scopeId || String(scopes[0]?.id || "")} onValueChange={setScopeId}><SelectTrigger className="w-[300px]"><SelectValue placeholder="Choose accessible Scope" /></SelectTrigger><SelectContent>{scopes.map((scope: any) => <SelectItem key={scope.id} value={String(scope.id)}>{scope.name} · {scope.scopeType.replaceAll("_", " ")}</SelectItem>)}</SelectContent></Select></CardContent></Card>

    {!currentScopeId ? <Card className="border-dashed"><CardContent className="py-12 text-center"><CircleDotDashed className="mx-auto h-8 w-8 text-muted-foreground/60" /><p className="mt-3 font-medium">No accessible Scope</p><p className="mt-1 text-sm text-muted-foreground">Create or receive membership in a Pulse Scope before configuring scorecards or strategy.</p></CardContent></Card> : <Tabs defaultValue="scorecard" className="space-y-4"><TabsList><TabsTrigger value="scorecard"><BarChart3 className="mr-1.5 h-3.5 w-3.5" />Scorecard</TabsTrigger><TabsTrigger value="alerts"><AlertTriangle className="mr-1.5 h-3.5 w-3.5" />Alerts <Badge variant="secondary" className="ml-1 h-4 px-1 text-[10px]">{alertCount}</Badge></TabsTrigger><TabsTrigger value="strategy"><Target className="mr-1.5 h-3.5 w-3.5" />VTO & strategy</TabsTrigger><TabsTrigger value="rocks"><Flag className="mr-1.5 h-3.5 w-3.5" />Rocks by owner</TabsTrigger></TabsList>
      <TabsContent value="scorecard" className="space-y-4"><Card><CardHeader><CardTitle>{activeScope?.name} scorecard</CardTitle><CardDescription>{scorecard?.periodSource === "pulse_calendar_service" ? "Period boundaries supplied by the central calendar service." : "Loading calendar-backed scorecard."}</CardDescription></CardHeader><CardContent>{scorecardLoading ? <div className="flex justify-center py-10"><Loader2 className="h-5 w-5 animate-spin" /></div> : scorecard?.rows.length ? <div className="space-y-2">{scorecard.rows.map((row: any) => <div key={row.id} className="grid gap-3 rounded-xl border p-3 md:grid-cols-[1.3fr_.7fr_.8fr_auto]"><div><div className="flex items-center gap-2"><p className="font-medium">{row.name}</p>{row.alert && <Badge variant="destructive">{row.alert.alertState}</Badge>}</div><p className="mt-1 text-xs text-muted-foreground">{row.period.type.replaceAll("_", " ")} · {row.period.startsOn} to {row.period.endsOn} · Owner: {row.ownerName || "Unassigned"}</p></div><div className="text-sm"><p className="text-xs text-muted-foreground">Target</p><p>{row.targetValue ?? "—"} {row.unit}</p></div><div className="text-sm"><p className="text-xs text-muted-foreground">Latest cell</p><p>{row.entry ? `${row.entry.value} ${row.unit}` : "No entry"}</p><p className="text-xs text-muted-foreground">{row.entry ? `Submitted by latest contributor` : ""}</p></div><div className="flex gap-2"><Input className="h-9 w-24" type="number" value={entryDrafts[row.id] ?? ""} onChange={(event) => setEntryDrafts((current) => ({ ...current, [row.id]: event.target.value }))} placeholder="Value" /><Button size="sm" onClick={() => recordEntry.mutate({ measurableId: row.id, scopeId: currentScopeId, value: Number(entryDrafts[row.id]) })} disabled={entryDrafts[row.id] === undefined || entryDrafts[row.id] === "" || recordEntry.isPending}><Save className="h-3.5 w-3.5" /></Button></div></div>)}</div> : <p className="py-8 text-center text-sm text-muted-foreground">No active measurable placements in this Scope.</p>}</CardContent></Card></TabsContent>
      <TabsContent value="alerts"><Card><CardHeader><CardTitle>Threshold alerts</CardTitle><CardDescription>Alert state is centrally evaluated when an entry is recorded. It is not a separately editable dashboard value.</CardDescription></CardHeader><CardContent className="space-y-2">{scorecard?.rows.filter((row: any) => row.alert).length ? scorecard.rows.filter((row: any) => row.alert).map((row: any) => <div key={row.id} className="flex items-center justify-between rounded-lg border border-destructive/30 bg-destructive/[0.03] p-3"><div><p className="font-medium">{row.name}</p><p className="text-sm text-muted-foreground">Observed {row.alert.observedValue} {row.unit} in {row.period.key}</p></div><Badge variant="destructive">{row.alert.alertState}</Badge></div>) : <p className="py-8 text-center text-sm text-muted-foreground">No warning or critical entries for this Scope period.</p>}</CardContent></Card></TabsContent>
      <TabsContent value="strategy"><Card><CardHeader><CardTitle>VTO planning view</CardTitle><CardDescription>This is a projection over the canonical strategy hierarchy. The status shown as a Scope presentation never overwrites the underlying node status.</CardDescription></CardHeader><CardContent className="space-y-2">{nodes.length ? nodes.map((entry: any) => <div key={entry.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-3"><div className="flex items-center gap-2"><ChevronRight className="h-4 w-4 text-muted-foreground" /><Badge variant="secondary">{NODE_LABELS[entry.nodeType]}</Badge><div><p className="font-medium">{entry.title}</p><p className="text-xs text-muted-foreground">Accountable ID {entry.accountablePersonId} · Responsible / displayed owner: {entry.displayedOwner} · Canonical status: {STATUS_LABELS[entry.status]}</p></div></div><Select value={entry.status} onValueChange={(status) => setStatus.mutate({ nodeId: entry.id, status: status as any })}><SelectTrigger className="h-8 w-36"><SelectValue /></SelectTrigger><SelectContent>{Object.entries(STATUS_LABELS).map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></div>) : <p className="py-8 text-center text-sm text-muted-foreground">No strategy placements in this Scope. Start with a Vision node.</p>}</CardContent></Card></TabsContent>
      <TabsContent value="rocks"><div className="space-y-4">{strategy?.rockGroups.length ? strategy.rockGroups.map((group: any) => <Card key={`${group.owner.personId ?? "unassigned"}`}><CardHeader className="pb-3"><CardTitle className="flex items-center gap-2 text-base"><UsersRound className="h-4 w-4 text-primary" />{group.owner.name}</CardTitle><CardDescription>{group.owner.personId ? "Displayed owner derives from active Responsible RACI assignment." : "No Responsible assignment; retained explicitly rather than disappearing."}</CardDescription></CardHeader><CardContent className="space-y-2">{group.rocks.map((rock: any) => <div key={rock.id} className="flex items-center justify-between rounded-lg border p-3"><div><p className="font-medium">{rock.title}</p><p className="text-xs text-muted-foreground">Canonical: {STATUS_LABELS[rock.status]} {rock.presentationStatus ? `· Scope presentation: ${STATUS_LABELS[rock.presentationStatus]}` : ""}</p></div><Badge variant={rock.status === "complete" ? "default" : "secondary"}>{STATUS_LABELS[rock.status]}</Badge></div>)}</CardContent></Card>) : <Card className="border-dashed"><CardContent className="py-10 text-center text-sm text-muted-foreground">No Quarterly Rocks after canonical filters. Unassigned rocks will appear in their own group when present.</CardContent></Card>}</div></TabsContent>
    </Tabs>}

    <Dialog open={measurableOpen} onOpenChange={setMeasurableOpen}><DialogContent><DialogHeader><DialogTitle>Create canonical measurable</DialogTitle><DialogDescription>One definition can be placed in multiple Scopes. It has no meeting-routing field, and period cells are created only through the calendar service.</DialogDescription></DialogHeader><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2 sm:col-span-2"><Label>Name</Label><Input value={measurable.name} onChange={(event) => setMeasurable({ ...measurable, name: event.target.value })} placeholder="Weekly appointments" /></div><div className="space-y-2"><Label>Unit</Label><Input value={measurable.unit} onChange={(event) => setMeasurable({ ...measurable, unit: event.target.value })} /></div><div className="space-y-2"><Label>Cadence</Label><Select value={measurable.cadence} onValueChange={(value) => setMeasurable({ ...measurable, cadence: value as any })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="weekly">Weekly</SelectItem><SelectItem value="monthly">Monthly</SelectItem><SelectItem value="quarterly">Quarterly</SelectItem></SelectContent></Select></div><div className="space-y-2"><Label>Target</Label><Input type="number" value={measurable.targetValue} onChange={(event) => setMeasurable({ ...measurable, targetValue: event.target.value })} /></div><div className="space-y-2"><Label>Owner</Label><Select value={measurable.ownerPersonId} onValueChange={(value) => setMeasurable({ ...measurable, ownerPersonId: value })}><SelectTrigger><SelectValue placeholder="Optional owner" /></SelectTrigger><SelectContent>{people.map((person: any) => <SelectItem key={person.id} value={String(person.id)}>{person.displayName}</SelectItem>)}</SelectContent></Select></div></div><DialogFooter><Button variant="outline" onClick={() => setMeasurableOpen(false)}>Cancel</Button><Button onClick={() => createMeasurable.mutate({ name: measurable.name, unit: measurable.unit, cadence: measurable.cadence, direction: measurable.direction, targetValue: measurable.targetValue ? Number(measurable.targetValue) : null, warningValue: measurable.warningValue ? Number(measurable.warningValue) : null, criticalValue: measurable.criticalValue ? Number(measurable.criticalValue) : null, ownerPersonId: measurable.ownerPersonId ? Number(measurable.ownerPersonId) : null, placementScopeIds: [currentScopeId] })} disabled={!measurable.name.trim() || createMeasurable.isPending}>Create</Button></DialogFooter></DialogContent></Dialog>

    <Dialog open={strategyOpen} onOpenChange={setStrategyOpen}><DialogContent className="max-w-xl"><DialogHeader><DialogTitle>Create strategy node</DialogTitle><DialogDescription>One hierarchy only. Accountable is required; Responsible determines the displayed owner and may be left blank only for explicit Unassigned grouping.</DialogDescription></DialogHeader><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label>Type</Label><Select value={node.nodeType} onValueChange={(value) => setNode({ ...node, nodeType: value as any, parentId: "" })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{Object.entries(NODE_LABELS).map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></div>{node.nodeType !== "vision" && <div className="space-y-2"><Label>Required parent</Label><Select value={node.parentId} onValueChange={(value) => setNode({ ...node, parentId: value })}><SelectTrigger><SelectValue placeholder="Choose parent" /></SelectTrigger><SelectContent>{potentialParents.map((parent: any) => <SelectItem key={parent.id} value={String(parent.id)}>{parent.title}</SelectItem>)}</SelectContent></Select></div>}<div className="space-y-2 sm:col-span-2"><Label>Title</Label><Input value={node.title} onChange={(event) => setNode({ ...node, title: event.target.value })} /></div><div className="space-y-2"><Label>Accountable</Label><Select value={node.accountablePersonId} onValueChange={(value) => setNode({ ...node, accountablePersonId: value })}><SelectTrigger><SelectValue placeholder="Required" /></SelectTrigger><SelectContent>{people.map((person: any) => <SelectItem key={person.id} value={String(person.id)}>{person.displayName}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Responsible / owner</Label><Select value={node.responsiblePersonId} onValueChange={(value) => setNode({ ...node, responsiblePersonId: value })}><SelectTrigger><SelectValue placeholder="Optional · Unassigned otherwise" /></SelectTrigger><SelectContent>{people.map((person: any) => <SelectItem key={person.id} value={String(person.id)}>{person.displayName}</SelectItem>)}</SelectContent></Select></div></div><DialogFooter><Button variant="outline" onClick={() => setStrategyOpen(false)}>Cancel</Button><Button onClick={() => createNode.mutate({ nodeType: node.nodeType, parentId: node.parentId ? Number(node.parentId) : null, title: node.title, accountablePersonId: Number(node.accountablePersonId), responsiblePersonId: node.responsiblePersonId ? Number(node.responsiblePersonId) : null, placementScopeIds: [currentScopeId] })} disabled={!node.title.trim() || !node.accountablePersonId || (node.nodeType !== "vision" && !node.parentId) || createNode.isPending}>Create node</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
