import { useMemo, useState } from "react";
import { trpc } from "@/lib/trpc";
import { Activity, BarChart3, CheckSquare2, Flame, Gauge, ListTodo, Loader2, Target, UsersRound } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

function Metric({ label, value, detail }: { label: string; value: string | number; detail?: string }) { return <Card><CardHeader className="pb-2"><CardDescription>{label}</CardDescription><CardTitle className="text-2xl">{value}</CardTitle></CardHeader>{detail && <CardContent className="pt-0 text-xs text-muted-foreground">{detail}</CardContent>}</Card>; }
function WorkRows({ items, empty }: { items: any[]; empty: string }) { return items.length ? <div className="space-y-2">{items.map((item) => <div key={item.id} className="rounded-lg border p-3"><div className="flex flex-wrap items-center gap-2"><Badge variant="secondary">{item.status.replaceAll("_", " ")}</Badge><p className="font-medium">{item.title}</p><span className="text-xs text-muted-foreground">{item.sourceLabel}</span></div><p className="mt-1 text-xs text-muted-foreground">Owner: {item.owner?.displayName ?? "Unassigned"} · Scope: {item.currentScope?.name ?? "Unavailable"} · {item.activity?.length ?? 0} activity entries</p></div>)}</div> : <p className="py-8 text-center text-sm text-muted-foreground">{empty}</p>; }

export function PulseTeamsDashboardPanel() {
  const { data: scopes = [] } = trpc.pulse.visibleScopes.useQuery(undefined, { staleTime: 10000 });
  const teams = useMemo(() => scopes.filter((scope: any) => scope.scopeType === "team"), [scopes]);
  const [teamScopeId, setTeamScopeId] = useState("");
  const activeTeamId = Number(teamScopeId || teams[0]?.id || 0);
  const dashboard = trpc.pulse.teamDashboard.useQuery({ teamScopeId: activeTeamId }, { enabled: !!activeTeamId, staleTime: 5000 });
  const data: any = dashboard.data;
  if (!teams.length) return <Card className="border-dashed"><CardContent className="py-14 text-center"><UsersRound className="mx-auto h-9 w-9 text-muted-foreground/60" /><p className="mt-4 font-semibold">No accessible Team Scopes</p><p className="mt-1 text-sm text-muted-foreground">Create a Team Scope and use standard Pulse membership before opening its dashboard.</p></CardContent></Card>;
  return <div className="space-y-4"><Card className="border-primary/20 bg-gradient-to-br from-primary/[0.05] to-transparent"><CardHeader className="gap-4 sm:flex-row sm:items-start sm:justify-between"><div><CardTitle>Team dashboard</CardTitle><CardDescription className="mt-1 max-w-3xl">One scoped query drives Overview, To-Dos, Rocks, Workload, Productivity, and Issues. Team links are explicit and directional; they never expand membership, content access, or cascade audiences.</CardDescription></div><Select value={String(activeTeamId)} onValueChange={setTeamScopeId}><SelectTrigger className="w-full sm:w-64"><SelectValue /></SelectTrigger><SelectContent>{teams.map((team: any) => <SelectItem key={team.id} value={String(team.id)}>{team.name}</SelectItem>)}</SelectContent></Select></CardHeader></Card>
    {dashboard.isLoading ? <div className="flex justify-center py-20"><Loader2 className="h-6 w-6 animate-spin" /></div> : dashboard.error ? <Card><CardContent className="py-10 text-center text-sm text-destructive">{dashboard.error.message}</CardContent></Card> : data && <Tabs defaultValue="overview" className="space-y-4"><TabsList className="h-auto max-w-full justify-start gap-1 overflow-x-auto"><TabsTrigger value="overview"><Gauge className="mr-1.5 h-3.5 w-3.5" />Overview</TabsTrigger><TabsTrigger value="todos"><ListTodo className="mr-1.5 h-3.5 w-3.5" />To-Dos</TabsTrigger><TabsTrigger value="rocks"><Target className="mr-1.5 h-3.5 w-3.5" />Rocks</TabsTrigger><TabsTrigger value="workload"><Activity className="mr-1.5 h-3.5 w-3.5" />Workload</TabsTrigger><TabsTrigger value="productivity"><BarChart3 className="mr-1.5 h-3.5 w-3.5" />Productivity</TabsTrigger><TabsTrigger value="issues"><Flame className="mr-1.5 h-3.5 w-3.5" />Issues</TabsTrigger></TabsList>
      <TabsContent value="overview" className="space-y-4"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Direct Team To-Dos" value={data.overview.directTodoCount} detail="Primary Scope is this Team" /><Metric label="Linked meeting-origin To-Dos" value={data.overview.linkedMeetingOriginTodoCount} detail="Only via work_rollup_from" /><Metric label="Direct Team Issues" value={data.overview.issueCount} detail="Never inherited from L10 links" /><Metric label="Active capacity items" value={data.overview.activeTodoCount} detail="Skipped recurring excluded" /></div><Card><CardHeader><CardTitle>Scoped relationships</CardTitle><CardDescription>These relationship types are independent configuration; none grants people or content access.</CardDescription></CardHeader><CardContent className="grid gap-2 md:grid-cols-3">{data.links.length ? data.links.map((link: any) => <div key={link.id} className="rounded-lg border p-3"><Badge variant="secondary">{link.relationshipType.replaceAll("_", " ")}</Badge><p className="mt-2 text-sm font-medium">{link.l10Name}</p></div>) : <p className="text-sm text-muted-foreground">No Team-to-L10 relationships configured.</p>}</CardContent></Card><Card><CardHeader><CardTitle>Policy statements</CardTitle></CardHeader><CardContent className="grid gap-2 text-sm md:grid-cols-2"><div className="rounded-lg bg-muted p-3"><strong>To-Dos:</strong> {data.policies.todos}</div><div className="rounded-lg bg-muted p-3"><strong>Issues:</strong> {data.policies.issues}</div></CardContent></Card></TabsContent>
      <TabsContent value="todos"><Card><CardHeader><CardTitle>Team To-Dos</CardTitle><CardDescription>Direct Team work plus qualifying L10 meeting-origin work only. The linked-meeting rule is independent from cascade and reporting links.</CardDescription></CardHeader><CardContent><WorkRows items={data.todos.items} empty="No To-Dos meet the Team policy." /></CardContent></Card></TabsContent>
      <TabsContent value="issues"><Card><CardHeader><CardTitle>Team Issues</CardTitle><CardDescription>Direct Team Scope Issues only. L10 links and meeting provenance do not affect this panel.</CardDescription></CardHeader><CardContent><WorkRows items={data.issues.items} empty="No direct Team Issues." /></CardContent></Card></TabsContent>
      <TabsContent value="rocks"><Card><CardHeader><CardTitle>Rocks by owner</CardTitle><CardDescription>Filters are applied before owner grouping. Responsible determines displayed owner; Unassigned remains its own group.</CardDescription></CardHeader><CardContent className="space-y-4">{data.rocks.groups.length ? data.rocks.groups.map((group: any) => <div key={group.owner}><p className="mb-2 text-sm font-semibold">{group.owner}</p><div className="space-y-2">{group.rocks.map((rock: any) => <div key={rock.id} className="rounded-lg border p-3"><div className="flex gap-2"><Badge variant="secondary">{rock.status.replaceAll("_", " ")}</Badge><span className="font-medium">{rock.title}</span></div></div>)}</div></div>) : <p className="text-sm text-muted-foreground">No Team-placed quarterly Rocks.</p>}</CardContent></Card></TabsContent>
      <TabsContent value="workload" className="space-y-4"><Card><CardHeader><CardTitle>Capacity workload</CardTitle><CardDescription>{data.workload.framing}</CardDescription></CardHeader><CardContent className="grid gap-3 lg:grid-cols-2">{data.workload.byPerson.map((person: any) => <div key={person.personId} className="rounded-lg border p-3"><div className="flex justify-between"><p className="font-medium">{person.name}</p><Badge>{person.total} active</Badge></div><div className="mt-3 flex h-3 overflow-hidden rounded bg-muted">{person.urgency.map((slice: any) => slice.count ? <div key={slice.priority} className={slice.priority === "urgent" ? "bg-red-500" : slice.priority === "high" ? "bg-orange-500" : slice.priority === "medium" ? "bg-amber-400" : "bg-sky-500"} style={{ width: `${Math.max(6, (slice.count / Math.max(person.total, 1)) * 100)}%` }} title={`${slice.priority}: ${slice.count}`} /> : null)}</div><p className="mt-2 text-xs text-muted-foreground">Urgency stack: {person.urgency.map((slice: any) => `${slice.priority} ${slice.count}`).join(" · ")}</p></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Assigned / completed heatmap</CardTitle><CardDescription>Operating-week columns are supplied by the central calendar service.</CardDescription></CardHeader><CardContent className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs text-muted-foreground"><th className="p-2">Person</th>{data.workload.heatmap[0]?.weeks.map((week: any) => <th key={week.key} className="p-2">{week.startsOn}</th>)}</tr></thead><tbody>{data.workload.heatmap.map((person: any) => <tr key={person.personId} className="border-b"><td className="p-2 font-medium">{person.name}</td>{person.weeks.map((week: any) => <td key={week.key} className="p-2"><span className="rounded bg-muted px-2 py-1">{week.assigned} / {week.completed}</span></td>)}</tr>)}</tbody></table></CardContent></Card></TabsContent>
      <TabsContent value="productivity"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Completed" value={data.productivity.completed} /><Metric label="Net flow" value={data.productivity.netFlow} /><Metric label="Overdue" value={data.productivity.overdue} /><Metric label="Median completion" value={data.productivity.medianCompletionDays === null ? "—" : `${data.productivity.medianCompletionDays.toFixed(1)}d`} /><Metric label="Carryover" value={data.productivity.carryover} /><Metric label="Aging median / max" value={`${data.productivity.agingDays.median ?? "—"} / ${data.productivity.agingDays.max ?? "—"}`} /><Metric label="Capture quality" value={`${data.productivity.captureQualityPercent}%`} /><Metric label="Skipped recurring excluded" value={data.productivity.skippedRecurringExcluded} /></div><Card className="mt-4"><CardContent className="py-4 text-sm text-muted-foreground">{data.productivity.framing}</CardContent></Card></TabsContent>
    </Tabs>}</div>;
}
