import { Target } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Progress } from "@/components/ui/progress";
import { trpc } from "@/lib/trpc";

function format(value: number | null, unit: string) { if (value == null) return "—"; if (unit === "currency") return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value); if (unit === "percentage") return `${value}%`; return new Intl.NumberFormat("en-US", { maximumFractionDigits: 1 }).format(value); }

function GoalsConfiguration({ meetingId, onChanged }: { meetingId: string; onChanged: () => void }) {
  const utils = trpc.useUtils(); const configuration = trpc.pulse.goals.configuration.useQuery({ meetingId });
  const add = trpc.pulse.goals.addGoal.useMutation({ onSuccess: () => { utils.pulse.goals.configuration.invalidate({ meetingId }); onChanged(); } });
  const remove = trpc.pulse.goals.removeGoal.useMutation({ onSuccess: () => { utils.pulse.goals.configuration.invalidate({ meetingId }); onChanged(); } });
  return <Dialog><DialogTrigger asChild><Button type="button" size="sm" variant="outline" className="min-h-11">Goal settings</Button></DialogTrigger><DialogContent className="max-h-[85vh] max-w-xl overflow-y-auto"><DialogHeader><DialogTitle>Goal settings</DialogTitle><DialogDescription>Pulse displays the dedicated SavvyOS company goals source. Agent goals and market goals are not used here.</DialogDescription></DialogHeader><div className="space-y-5"><div><p className="font-medium">Shown in this meeting</p><div className="mt-2 space-y-2">{(configuration.data?.mapped ?? []).map((goal: any) => <div key={goal.mappingId} className="flex min-h-11 items-center justify-between gap-3 rounded-lg bg-muted/50 px-3 py-2"><span>{goal.title}{goal.status !== "active" && <span className="ml-2 text-sm text-muted-foreground">({goal.status === "deleted" ? "deleted in SavvyOS" : "inactive in SavvyOS"})</span>}</span><Button type="button" variant="ghost" size="sm" className="min-h-11" onClick={() => remove.mutate({ meetingId, mappingId: goal.mappingId })}>Remove</Button></div>)}{!(configuration.data?.mapped ?? []).length && <p className="text-sm text-muted-foreground">No company goals are selected for this meeting.</p>}</div></div><div><p className="font-medium">Add an active SavvyOS company goal</p><div className="mt-2 space-y-2">{(configuration.data?.available ?? []).filter((goal: any) => !(configuration.data?.mapped ?? []).some((mapped: any) => mapped.goalId === goal.id)).map((goal: any) => <div key={goal.id} className="flex min-h-11 items-center justify-between gap-3 rounded-lg border border-border px-3 py-2"><span><span className="block">{goal.title}</span><span className="text-sm text-muted-foreground">{goal.ownerName ?? "Unassigned"} · {goal.year}</span></span><Button type="button" size="sm" variant="outline" className="min-h-11" onClick={() => add.mutate({ meetingId, goalId: goal.id })}>Add</Button></div>)}</div></div></div></DialogContent></Dialog>;
}

export function PulseGoals({ section, meetingId, canConfigure = false, onChanged }: { section: any; meetingId: string; canConfigure?: boolean; onChanged: () => void }) {
  const goals = section.items ?? [];
  return <div className="space-y-3"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-sm text-muted-foreground">Company goals from SavvyOS</p>{canConfigure && <GoalsConfiguration meetingId={meetingId} onChanged={onChanged} />}</div>{canConfigure && (section.meta?.configurationNotes ?? []).map((note: any) => <p key={note.mappingId} className="rounded-lg bg-muted/60 p-3 text-sm text-muted-foreground">{note.note}</p>)}{!goals.length && <p className="rounded-lg bg-muted/60 p-3 text-sm text-muted-foreground">No active SavvyOS company goals are selected for this meeting.</p>}<div className="space-y-3">{goals.map((goal: any) => <article key={goal.goalId} className="rounded-lg border border-border p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-medium">{goal.title}</h3><p className="mt-1 text-sm text-muted-foreground">{goal.owner?.name ?? "Unassigned"} · {goal.year}</p></div><Target className="h-5 w-5 text-primary" aria-hidden="true" /></div>{goal.description && <p className="mt-3 text-sm text-muted-foreground">{goal.description}</p>}<div className="mt-4"><div className="flex justify-between gap-3 text-sm"><span>{format(goal.current, goal.unit)} of {format(goal.target, goal.unit)}</span><span className="font-medium">{goal.percentComplete == null ? "No target" : `${goal.percentComplete}%`}</span></div><Progress className="mt-2 h-2" value={goal.percentComplete ?? 0} /></div></article>)}</div></div>;
}
